package com.vhanma.scalaraudioforge

import kotlin.math.max

enum class RecommendedRoute(val label:String){FULL_CHAIN("FULL CHAIN"),FULL_MERGE("FULL MERGE"),SIDE_BY_SIDE("SIDE-BY-SIDE")}
enum class ConflictLevel(val label:String){LOW("LOW"),MEDIUM("MEDIUM"),HIGH("HIGH")}
data class ExpectationScores(val rhythmic:Int,val harmonic:Int,val spatial:Int,val phase:Int,val carrier:Int,val temporal:Int,val information:Int){fun values():IntArray=intArrayOf(rhythmic,harmonic,spatial,phase,carrier,temporal,information)}
data class ComboReport(val methods:List<TransformKind>,val summary:String,val why:String,val route:RecommendedRoute,val conflict:ConflictLevel,val conflictReason:String,val bestUse:String,val scores:ExpectationScores){val title:String get()=methods.joinToString(" + "){it.title}}

object ComboEngine{
    val allPairs:List<ComboReport> by lazy{val kinds=TransformKind.entries;buildList{for(i in 0 until kinds.lastIndex)for(j in i+1 until kinds.size)add(analyze(listOf(kinds[i],kinds[j])))}}
    fun pair(a:TransformKind,b:TransformKind)=analyze(listOf(a,b))
    fun analyze(input:List<TransformKind>):ComboReport{
        val methods=input.distinct();if(methods.isEmpty())return ComboReport(emptyList(),"Dry conversion only.","No experimental DSP method is active.",RecommendedRoute.FULL_CHAIN,ConflictLevel.LOW,"No method conflict.","Normal format conversion.",ExpectationScores(0,0,0,0,0,0,0))
        val profiles=methods.map(MethodCatalog::profile);val traits=profiles.flatMap{it.traits}.toSet();fun score(selector:(MethodProfile)->Int)=profiles.maxOf(selector).coerceIn(0,5)
        var rhythmic=score{it.rhythmic};var harmonic=score{it.harmonic};var spatial=score{it.spatial};var phase=score{it.phase};var carrier=score{it.carrier};var temporal=score{it.temporal};var information=score{it.information}
        val notes=mutableListOf<String>();val reasons=mutableListOf<String>();var conflict=ConflictLevel.LOW;val conflicts=mutableListOf<String>()
        val envelopeCount=profiles.count{MethodTrait.ENVELOPE in it.traits};val carrierCount=profiles.count{MethodTrait.CARRIER in it.traits};val phaseCount=profiles.count{MethodTrait.PHASE in it.traits};val reverseCount=profiles.count{MethodTrait.REVERSE in it.traits}
        if(envelopeCount>=2){rhythmic=max(rhythmic,5);notes+="compound rhythmic motion and beating between envelope patterns";reasons+="multiple methods reshape amplitude over time";if(envelopeCount>=3){conflict=maxConflict(conflict,ConflictLevel.MEDIUM);conflicts+="three or more envelope methods can make the rhythmic structure crowded"}}
        if(MethodTrait.ENVELOPE in traits&&MethodTrait.CARRIER in traits){carrier=max(carrier,4);rhythmic=max(rhythmic,4);notes+="a carrier structure that breathes or pulses with the low-rate modulation";reasons+="carrier energy and envelope motion affect different parts of the signal"}
        if(MethodTrait.HARMONIC in traits&&MethodTrait.STEREO in traits){harmonic=max(harmonic,5);spatial=max(spatial,4);notes+="richer harmonic body spread across a moving or separated stereo field";reasons+="harmonic layers add tonal density while stereo processing redistributes it"}
        if(MethodTrait.PHASE in traits&&MethodTrait.STEREO in traits){phase=5;spatial=5;notes+="strong stereo geometry and phase-dependent center changes";reasons+="both methods change the relationship between left and right channels";conflict=maxConflict(conflict,ConflictLevel.MEDIUM);conflicts+="phase-heavy stereo combinations may thin or shift center content"}
        if(MethodTrait.MONO_CENTER in traits&&(MethodTrait.STEREO in traits||MethodTrait.BINAURAL in traits)){conflict=ConflictLevel.HIGH;conflicts+="center projection fights stereo/binaural separation when chained; side-by-side keeps both complete";notes+="a contrast between center-focused and stereo-focused versions of the source";reasons+="one method collapses channel differences while the other depends on them"}
        if(reverseCount>=2){temporal=5;phase=max(phase,4);notes+="dense mirrored temporal texture and unusual attack/decay behavior";reasons+="multiple methods pair local windows with reversed or conjugated copies";conflict=maxConflict(conflict,ConflictLevel.MEDIUM);conflicts+="multiple reverse/conjugate stages may smear transients heavily"}
        if(MethodTrait.CODED in traits&&MethodTrait.CHIRP in traits){information=5;carrier=max(carrier,5);notes+="a highly recognizable coded/swept signal fingerprint";reasons+="deterministic coding and chirp structure provide complementary correlation cues"}
        if(carrierCount>=3){conflict=maxConflict(conflict,ConflictLevel.MEDIUM);conflicts+="several carrier families can mask quiet source detail or one another"}
        if(phaseCount>=2&&MethodTrait.MONO_CENTER in traits){conflict=ConflictLevel.HIGH;conflicts+="strong phase manipulation followed by center projection can cancel information unpredictably"}
        if(notes.isEmpty())notes+=when{rhythmic>=4->"clear rhythmic reshaping with the second method adding a distinct secondary texture";spatial>=4->"strong spatial reshaping with an additional independent signal character";carrier>=4->"a more structured carrier-rich signal while preserving the other method's main behavior";temporal>=4->"noticeable local time-symmetry texture with a second independent transformation";else->"both full transformations acting together without either being reduced to a percentage"}
        if(reasons.isEmpty())reasons+="each method receives the complete source or the complete preceding result, depending on routing"
        val scores=ExpectationScores(rhythmic,harmonic,spatial,phase,carrier,temporal,information);val route=recommendRoute(methods,traits,conflict);val use=buildUse(scores,traits);val conflictReason=if(conflicts.isEmpty())"No major structural conflict predicted. Listen for clipping or masking with dense source material." else conflicts.distinct().joinToString("; ")
        return ComboReport(methods,"Expect "+notes.distinct().joinToString(", ")+".",reasons.distinct().joinToString("; ").replaceFirstChar{it.uppercase()}+".",route,conflict,conflictReason,use,scores)
    }
    private fun recommendRoute(methods:List<TransformKind>,traits:Set<MethodTrait>,conflict:ConflictLevel):RecommendedRoute{if(methods.size==1)return RecommendedRoute.FULL_CHAIN;if(MethodTrait.MONO_CENTER in traits&&(MethodTrait.STEREO in traits||MethodTrait.BINAURAL in traits))return RecommendedRoute.SIDE_BY_SIDE;if(conflict==ConflictLevel.HIGH)return RecommendedRoute.SIDE_BY_SIDE;if(MethodTrait.CODED in traits&&MethodTrait.CHIRP in traits)return RecommendedRoute.FULL_MERGE;if(MethodTrait.PHASE in traits&&MethodTrait.STEREO in traits)return RecommendedRoute.SIDE_BY_SIDE;if(MethodTrait.REVERSE in traits&&MethodTrait.ENVELOPE in traits)return RecommendedRoute.FULL_CHAIN;return RecommendedRoute.FULL_MERGE}
    private fun buildUse(scores:ExpectationScores,traits:Set<MethodTrait>)=when{scores.information>=5->"Pattern/correlation and information-carrier experiments; FULL MERGE keeps independent fingerprints intact.";scores.spatial>=5->"Headphone/stereo spatial experiments and left/right comparison.";scores.temporal>=5->"Mirrored-window, conjugate, and time-symmetry texture experiments.";scores.rhythmic>=5&&scores.harmonic>=4->"Pulsed resonance-style experiments where rhythmic motion rides on harmonic structure.";scores.rhythmic>=5->"Low-rate modulation, beating, and envelope interaction experiments.";scores.harmonic>=5->"Tonal resonance and harmonic-carrier experiments.";MethodTrait.MONO_CENTER in traits->"Center-field reference and mono/longitudinal-style comparison.";else->"General full-method comparison and reproducible DSP experiments."}
    private fun maxConflict(a:ConflictLevel,b:ConflictLevel)=if(a.ordinal>=b.ordinal)a else b
}
