package com.vhanma.scalaraudioforge

enum class MethodTrait { ENVELOPE, CARRIER, HARMONIC, STEREO, PHASE, REVERSE, GEOMETRY, CODED, BINAURAL, CHIRP, BIO_LABEL, ELF, MONO_CENTER, SWEEP }
enum class DiagramType { ENVELOPE, CARRIER, STEREO_PAIR, HARMONICS, PHASE_ROTATE, OPPOSED, STANDING, REVERSE_PAIR, LADDER, SWEEP, CHIRP, CENTER, CODED }

data class MethodProfile(val traits: Set<MethodTrait>, val expectedSound: String, val bestUse: String, val combinesWell: String, val conflicts: String, val diagramType: DiagramType, val frequencies: List<Double> = emptyList(), val rhythmic: Int = 0, val harmonic: Int = 0, val spatial: Int = 0, val phase: Int = 0, val carrier: Int = 0, val temporal: Int = 0, val information: Int = 0)

object MethodCatalog {
    fun profile(kind: TransformKind): MethodProfile = when (kind) {
        TransformKind.PUHARICH_8 -> MethodProfile(setOf(MethodTrait.ENVELOPE,MethodTrait.ELF),"Slow, obvious amplitude pulsing on sustained material.","ELF-style rhythmic experiments and carrier-plus-envelope chains.","256 Hz Control, Tesla Harmonics, Information Carrier, Schumann 7.83 Hz.","Stacking many envelope methods can make volume motion overly dense.",DiagramType.ENVELOPE,listOf(8.0),rhythmic=5,carrier=1)
        TransformKind.SCHUMANN_783 -> MethodProfile(setOf(MethodTrait.ENVELOPE,MethodTrait.ELF),"Slow amplitude movement at a rhythm very close to 8 Hz.","Close-frequency beating experiments and low-rate modulation layers.","Puharich 8 Hz, Gateway Stereo, Tesla Harmonics.","Several nearby envelope methods can create pronounced beating and level motion.",DiagramType.ENVELOPE,listOf(7.83),rhythmic=5)
        TransformKind.CONTROL_256 -> MethodProfile(setOf(MethodTrait.CARRIER),"A quiet stable tonal reference underneath the source.","Reference/carrier layers and repeatable timing-oriented stacks.","Puharich 8 Hz, Information Carrier, PHASER Sweep.","Can become tonal or whistle-like when combined with many carrier layers.",DiagramType.CARRIER,listOf(256.0),carrier=5,harmonic=2)
        TransformKind.GATEWAY_STEREO -> MethodProfile(setOf(MethodTrait.STEREO,MethodTrait.CARRIER,MethodTrait.BINAURAL),"A headphone-focused stereo carrier field with different left/right tones.","Stereo/headphone experiments and side-by-side routing.","Puharich 8 Hz, Schumann 7.83 Hz, Tesla Harmonics.","Center-projecting or phase-opposed methods can substantially change the intended stereo relationship.",DiagramType.STEREO_PAIR,listOf(252.0,260.0),spatial=5,carrier=5,rhythmic=2)
        TransformKind.TESLA_HARMONICS -> MethodProfile(setOf(MethodTrait.CARRIER,MethodTrait.HARMONIC),"Richer tonal density from several related sinusoidal components.","Resonance-style layers and harmonic carrier beds.","Puharich 8 Hz, Meyl Phase Vortex, Gateway Stereo.","Multiple carrier-heavy methods can mask quiet source detail.",DiagramType.HARMONICS,listOf(144.0,432.0,864.0),harmonic=5,carrier=5)
        TransformKind.MEYL_VORTEX -> MethodProfile(setOf(MethodTrait.STEREO,MethodTrait.PHASE),"Slow left/right rotation and changing stereo geometry.","Spatial experiments, headphones, and phase-oriented combinations.","Tesla Harmonics, Puharich 8 Hz, Information Carrier.","Other strong phase or mono-center methods may thin or collapse parts of the stereo image.",DiagramType.PHASE_ROTATE,spatial=5,phase=5)
        TransformKind.PHASE_OPPOSED -> MethodProfile(setOf(MethodTrait.PHASE,MethodTrait.STEREO,MethodTrait.GEOMETRY),"A widened/opposed differential field with reduced common-center information.","Phase cancellation studies and left/right differential experiments.","Standing-Wave Nodes, Meyl Phase Vortex, Chirp / Spread Pattern.","Mono-compatible content may thin strongly. Pairing with center projection creates an intentional conflict.",DiagramType.OPPOSED,spatial=5,phase=5)
        TransformKind.STANDING_WAVE -> MethodProfile(setOf(MethodTrait.ENVELOPE,MethodTrait.GEOMETRY),"Repeating deep amplitude nodes and antinodes.","Node-pattern demonstrations and geometric modulation experiments.","Phase-Opposed Pair, Puharich 8 Hz, Tesla Harmonics.","Can create strong level pumping when chained after another deep envelope.",DiagramType.STANDING,listOf(3.0),rhythmic=4,phase=1)
        TransformKind.ADVANCED_RETARDED -> MethodProfile(setOf(MethodTrait.REVERSE,MethodTrait.GEOMETRY),"Locally mirrored texture, smeared attacks, and forward/reverse symmetry.","Temporal-symmetry and mirrored-window experiments.","Bearden Conjugate Pair, Schumann 7.83 Hz, Information Carrier.","Transient-heavy material can sound blurred because each local window is paired with its reverse.",DiagramType.REVERSE_PAIR,temporal=5,phase=2)
        TransformKind.DNA_WATER -> MethodProfile(setOf(MethodTrait.HARMONIC,MethodTrait.CARRIER,MethodTrait.BIO_LABEL),"A harmonic amplitude texture tied to a 256 Hz family.","Bio/DNA/water-labeled experiments where the exact DSP recipe should remain reproducible.","Puharich 8 Hz, Information Carrier, PHASER Sweep.","The biological label should not be confused with a measured biological effect.",DiagramType.LADDER,listOf(256.0,512.0,1024.0),harmonic=5,carrier=4)
        TransformKind.TRIPLE_ELF -> MethodProfile(setOf(MethodTrait.ENVELOPE,MethodTrait.ELF),"Complex slow beating from three nearby envelope rates.","Close-frequency interaction and compound ELF-style modulation.","Tesla Harmonics, Information Carrier, Gateway Stereo.","Adding more low-rate envelopes can make the total modulation hard to separate by ear.",DiagramType.ENVELOPE,listOf(7.83,8.0,9.0),rhythmic=5)
        TransformKind.BRAIN_LADDER -> MethodProfile(setOf(MethodTrait.ENVELOPE,MethodTrait.ELF,MethodTrait.SWEEP),"The rhythmic modulation character changes every few seconds.","Dynamic low-frequency envelope experiments instead of one fixed rate.","Tesla Harmonics, 256 Hz Control, Gateway Stereo.","Combining with several other moving envelopes can become rhythmically crowded.",DiagramType.LADDER,listOf(4.0,7.83,8.0,10.0,20.0,40.0),rhythmic=5)
        TransformKind.PHASER_SWEEP -> MethodProfile(setOf(MethodTrait.ENVELOPE,MethodTrait.SWEEP),"Faster moving amplitude texture sweeping through 20-200 Hz.","Puharich PHASER-inspired moving-modulation experiments.","256 Hz Control, DNA / Water Harmonics, Information Carrier.","Can add a buzzy or tremolo-like texture to sparse material.",DiagramType.SWEEP,listOf(20.0,200.0),rhythmic=4,carrier=2)
        TransformKind.CHIRP_SPREAD -> MethodProfile(setOf(MethodTrait.CHIRP,MethodTrait.CODED,MethodTrait.CARRIER),"A repeating swept-pattern texture designed to have a recognizable correlation signature.","Information-transfer-style signal tests and pattern detection experiments.","Information Carrier, Phase-Opposed Pair, Puharich 8 Hz.","Carrier-heavy combinations can become sonically dense; side-by-side routing keeps signatures easier to separate.",DiagramType.CHIRP,listOf(300.0,3000.0),carrier=4,information=5)
        TransformKind.LONGITUDINAL_MONO -> MethodProfile(setOf(MethodTrait.MONO_CENTER,MethodTrait.GEOMETRY),"Collapses the signal toward one shared center image.","Center-field/longitudinal-style digital simulations and mono-reference comparisons.","Standing-Wave Nodes, Puharich 8 Hz, Information Carrier.","Strongly conflicts with stereo-vortex, binaural, and phase-opposed methods if chained afterward.",DiagramType.CENTER,spatial=1,phase=2)
        TransformKind.BEARDEN_CONJUGATE -> MethodProfile(setOf(MethodTrait.REVERSE,MethodTrait.PHASE,MethodTrait.GEOMETRY),"Mirrored texture with polarity opposition and strong local temporal reshaping.","Conjugate/opposed-window simulations and temporal geometry experiments.","Advanced / Retarded Pair, Information Carrier, Standing-Wave Nodes.","May substantially reduce or smear transient information and can interact strongly with other phase methods.",DiagramType.REVERSE_PAIR,temporal=5,phase=5)
        TransformKind.INFORMATION_CARRIER -> MethodProfile(setOf(MethodTrait.CODED,MethodTrait.CARRIER),"A quiet repeatable coded reference pattern laid under the source.","Reproducible signal fingerprints, correlation tests, and information-pattern stacks.","Chirp / Spread Pattern, 256 Hz Control, Puharich 8 Hz.","Multiple unrelated carrier layers can make the fingerprint harder to isolate acoustically.",DiagramType.CODED,listOf(256.0),carrier=5,information=5)
    }
    fun familySymbol(category: WaveCategory): String = when(category){ WaveCategory.PUHARICH_ELF->"P8";WaveCategory.SCHUMANN_BRAIN->"SR";WaveCategory.TESLA_RESONANCE->"T";WaveCategory.SCALAR_LONGITUDINAL->"SL";WaveCategory.MEYL->"M";WaveCategory.BEARDEN->"B";WaveCategory.GATEWAY->"GW";WaveCategory.BIO_DNA->"BIO";WaveCategory.INFORMATION->"INF";WaveCategory.WAVE_GEOMETRY->"WG" }
    fun familyColor(category: WaveCategory): Int = when(category){ WaveCategory.PUHARICH_ELF->0xFF9C7CFF.toInt();WaveCategory.SCHUMANN_BRAIN->0xFF55B9FF.toInt();WaveCategory.TESLA_RESONANCE->0xFFFFB84D.toInt();WaveCategory.SCALAR_LONGITUDINAL->0xFF75E0C1.toInt();WaveCategory.MEYL->0xFFFF77D2.toInt();WaveCategory.BEARDEN->0xFFB9A7FF.toInt();WaveCategory.GATEWAY->0xFF62D9FF.toInt();WaveCategory.BIO_DNA->0xFF78D878.toInt();WaveCategory.INFORMATION->0xFFFFCF66.toInt();WaveCategory.WAVE_GEOMETRY->0xFFAEB7C9.toInt() }
}
