package com.vhanma.scalaraudioforge

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.util.AttributeSet
import android.view.MotionEvent
import android.view.ScaleGestureDetector
import android.view.View
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sqrt

class WaveformView @JvmOverloads constructor(context:Context,attrs:AttributeSet?=null):View(context,attrs){
    private val grid=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.rgb(45,49,64);strokeWidth=1f};private val originalPaint=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.rgb(120,130,150);strokeWidth=2f};private val processedPaint=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.rgb(156,124,255);strokeWidth=2f};private val differencePaint=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.rgb(73,210,180);strokeWidth=2f};private val spectrumPaint=Paint(Paint.ANTI_ALIAS_FLAG).apply{strokeWidth=1f};private val textPaint=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.rgb(180,184,199);textSize=21f};private val titlePaint=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.WHITE;textSize=24f}
    private val originalHistory=ArrayList<Float>(9000);private val processedHistory=ArrayList<Float>(9000);private val differenceHistory=ArrayList<Float>(9000);private val spectrogram=ArrayList<FloatArray>(220);private var labels:List<String> = emptyList();private var zoom=1f;private var pan=0f;private var lastX=0f
    private val scaleDetector=ScaleGestureDetector(context,object:ScaleGestureDetector.SimpleOnScaleGestureListener(){override fun onScale(detector:ScaleGestureDetector):Boolean{zoom=(zoom*detector.scaleFactor).coerceIn(1f,24f);clampPan();invalidate();return true}})
    fun setWaveLabels(value:List<String>){labels=value.distinct().take(8);invalidate()}
    fun clearHistory(){originalHistory.clear();processedHistory.clear();differenceHistory.clear();spectrogram.clear();zoom=1f;pan=0f;invalidate()}
    fun appendComparison(original:FloatArray,processed:FloatArray){if(processed.isEmpty())return;val op=downsample(original,120);val pp=downsample(processed,120);val count=min(op.size,pp.size);for(i in 0 until count){originalHistory.add(op[i]);processedHistory.add(pp[i]);differenceHistory.add((pp[i]-op[i]).coerceIn(-1f,1f))};trim(originalHistory,9000);trim(processedHistory,9000);trim(differenceHistory,9000);spectrogram.add(spectrumOf(processed,42));if(spectrogram.size>220)spectrogram.subList(0,spectrogram.size-220).clear();clampPan();invalidate()}
    fun appendSamples(processed:FloatArray)=appendComparison(FloatArray(processed.size),processed)
    override fun onTouchEvent(event:MotionEvent):Boolean{scaleDetector.onTouchEvent(event);when(event.actionMasked){MotionEvent.ACTION_DOWN->{lastX=event.x;parent?.requestDisallowInterceptTouchEvent(true);return true};MotionEvent.ACTION_MOVE->{if(!scaleDetector.isInProgress&&processedHistory.size>1){val dx=event.x-lastX;lastX=event.x;val visible=visibleCount(processedHistory.size);val maxStart=max(0,processedHistory.size-visible);if(maxStart>0&&width>0)pan=(pan+(-dx/width*visible)/maxStart).coerceIn(0f,1f);invalidate()};return true};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{parent?.requestDisallowInterceptTouchEvent(false);return true}};return true}
    override fun onDraw(canvas:Canvas){super.onDraw(canvas);canvas.drawColor(Color.rgb(13,16,24));canvas.drawText("ORIGINAL / PROCESSED / DIFFERENCE",14f,28f,titlePaint);if(labels.isNotEmpty())canvas.drawText(labels.joinToString(" • ").take(100),14f,52f,textPaint);drawBand(canvas,originalHistory,height*0.15f,height*0.29f,originalPaint,"ORIGINAL");drawBand(canvas,processedHistory,height*0.31f,height*0.45f,processedPaint,"PROCESSED");drawBand(canvas,differenceHistory,height*0.47f,height*0.61f,differencePaint,"DIFFERENCE");canvas.drawText("PROCESSED SPECTROGRAM",14f,height*0.67f,titlePaint);drawSpectrogram(canvas,height*0.70f,height*0.93f);canvas.drawText("pinch = zoom   drag = scroll",14f,height-10f,textPaint)}
    private fun drawBand(canvas:Canvas,history:List<Float>,top:Float,bottom:Float,paint:Paint,title:String){val mid=(top+bottom)*0.5f;canvas.drawText(title,14f,top+20f,textPaint);canvas.drawLine(0f,mid,width.toFloat(),mid,grid);if(history.size<2)return;val count=visibleCount(history.size);val maxStart=max(0,history.size-count);val start=(pan*maxStart).toInt().coerceIn(0,maxStart);val end=min(history.size,start+count);if(end-start<2)return;val amp=(bottom-top)*0.38f;var px=0f;var py=mid;for(i in start until end){val local=i-start;val x=local.toFloat()/(end-start-1)*width;val y=mid-history[i].coerceIn(-1f,1f)*amp;if(local>0)canvas.drawLine(px,py,x,y,paint);px=x;py=y}}
    private fun drawSpectrogram(canvas:Canvas,top:Float,bottom:Float){if(spectrogram.isEmpty())return;val visibleCols=max(2,(spectrogram.size/zoom).toInt());val maxStart=max(0,spectrogram.size-visibleCols);val start=(pan*maxStart).toInt().coerceIn(0,maxStart);val end=min(spectrogram.size,start+visibleCols);if(end<=start)return;val colW=width.toFloat()/(end-start);val bins=spectrogram[start].size;val rowH=(bottom-top)/bins;for(column in start until end){val values=spectrogram[column];val x0=(column-start)*colW;for(bin in values.indices){val v=values[bin].coerceIn(0f,1f);val r=(30+180*v).toInt().coerceIn(0,255);val g=(45+190*v*v).toInt().coerceIn(0,255);val b=(70+150*(1f-v)).toInt().coerceIn(0,255);spectrumPaint.color=Color.rgb(r,g,b);val y1=bottom-bin*rowH;canvas.drawRect(x0,y1-rowH,x0+colW+1f,y1,spectrumPaint)}};canvas.drawLine(0f,top,width.toFloat(),top,grid)}
    private fun visibleCount(size:Int)=if(size<=0)0 else max(2,(size/zoom).toInt()).coerceAtMost(size);private fun clampPan(){pan=pan.coerceIn(0f,1f);if(zoom<=1.001f)pan=0f};private fun trim(list:ArrayList<Float>,maxSize:Int){if(list.size>maxSize)list.subList(0,list.size-maxSize).clear()}
    private fun downsample(input:FloatArray,maxPoints:Int):FloatArray{if(input.isEmpty())return FloatArray(0);if(input.size<=maxPoints)return input.copyOf();val out=FloatArray(maxPoints);val step=input.size.toDouble()/maxPoints;for(i in out.indices){val from=(i*step).toInt().coerceAtMost(input.lastIndex);val to=(((i+1)*step).toInt()).coerceAtMost(input.size);var peak=0f;for(j in from until max(from+1,to))if(abs(input[j])>abs(peak))peak=input[j];out[i]=peak};return out}
    private fun spectrumOf(input:FloatArray,bins:Int):FloatArray{val n=min(640,input.size);if(n<8)return FloatArray(bins);val out=FloatArray(bins);var maxMag=1e-9;for(k in 0 until bins){val fftBin=1+k*(n/2-1)/bins;var re=0.0;var im=0.0;for(i in 0 until n){val angle=2.0*PI*fftBin*i/n;val window=0.5-0.5*cos(2.0*PI*i/(n-1));val v=input[i]*window;re+=v*cos(angle);im-=v*kotlin.math.sin(angle)};val magnitude=sqrt(re*re+im*im);out[k]=magnitude.toFloat();if(magnitude>maxMag)maxMag=magnitude};for(i in out.indices)out[i]=sqrt(out[i]/maxMag.toFloat()).coerceIn(0f,1f);return out}
}
