/**
 * BioSonify Frequency Library
 * 565 entries across 8 categories
 * Sources: Gariaev, Rife, Solfeggio, Schumann, bioresonance research, organ resonance studies
 * All frequencies are documented — none are invented.
 */

export type FrequencyCategory =
  | 'DNA'
  | 'Solfeggio'
  | 'Brainwave'
  | 'Organ'
  | 'Superhuman'
  | 'WaveGenetics'
  | 'Rife'
  | 'Schumann';

export interface FrequencyEntry {
  id: string;
  name: string;
  hz: number;
  effect: string;
  source: string;
  category: FrequencyCategory;
}

export const FREQUENCY_LIBRARY: FrequencyEntry[] = [
  { id: 'rife-toxin-elimination-0', name: 'Toxin Elimination', hz: 0.5, effect: 'Toxin elimination, with #\\\'s 87,88,1,14,17,20,58.', source: 'Royal Rife', category: 'Rife' },
  { id: 'brainwave-brain-waves---delta-state-1', name: 'Brain Waves - Delta State', hz: 0.5, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'bw-delta', name: 'Delta — Deep Sleep', hz: 1.0, effect: 'Deep sleep, HGH release, cellular regeneration', source: 'Brainwave research', category: 'Brainwave' },
  { id: 'superhuman-mitochondrial-biogenesis-3', name: 'Mitochondrial Biogenesis', hz: 1.0, effect: 'Extremely low-frequency (ELF)-WMF', source: 'T Toda', category: 'Superhuman' },
  { id: 'org-heart', name: 'Heart Resonance', hz: 1.2, effect: 'Heart muscle resonance, cardiac coherence, HRV improvement', source: 'Bioresonance / HeartMath', category: 'Organ' },
  { id: 'rife-hiv-elimination-5', name: 'HIV Elimination', hz: 1.2, effect: 'HIV virus--elimination from circulating blood.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-hiv-virus-6', name: 'HIV virus', hz: 1.2, effect: 'HIV virus elimination', source: 'James Bare', category: 'Rife' },
  { id: 'gariaev-2', name: 'Gariaev 2 Hz Phantom', hz: 2.0, effect: 'DNA phantom field persistence frequency (Gariaev phantom effect)', source: 'Peter Gariaev', category: 'WaveGenetics' },
  { id: 'rife-sedative-effect-8', name: 'Sedative Effect', hz: 2.5, effect: 'Used for sedative effect.', source: 'Royal Rife', category: 'Rife' },
  { id: 'brainwave-stroke-9', name: 'Stroke', hz: 3.0, effect: 'Stroke treatment', source: 'James Bare', category: 'Brainwave' },
  { id: 'rife-depression-anxiety-10', name: 'Depression/Anxiety', hz: 3.5, effect: 'Depression & Anxiety.', source: 'Royal Rife', category: 'Rife' },
  { id: 'brainwave-depression---anxiety-11', name: 'Depression & Anxiety', hz: 3.5, effect: 'Reduces depression & anxiety', source: 'James Bare', category: 'Brainwave' },
  { id: 'brainwave-brain-waves---delta-state-12', name: 'Brain Waves - Delta State', hz: 3.5, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'rife-anger-irritibility-13', name: 'Anger/Irritibility', hz: 3.6, effect: 'Anger and irritibility.', source: 'Royal Rife', category: 'Rife' },
  { id: 'brainwave-anger-and-irritability-14', name: 'Anger and irritability', hz: 3.6, effect: 'Reduces anger and irritability', source: 'Rife/Stafford', category: 'Brainwave' },
  { id: 'rife-unsociable-behaviour-15', name: 'Unsociable Behaviour', hz: 3.9, effect: 'Unsociable behaviour.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-unsociable-behavior-16', name: 'Unsociable behavior', hz: 3.9, effect: 'Reduces unsociable behavior', source: 'James Bare', category: 'Rife' },
  { id: 'brainwave-brain-waves---theta-state-17', name: 'Brain Waves - Theta State', hz: 4.0, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'brainwave-relaxation--meditation--deeper-18', name: 'Relaxation, meditation, deeper sleep', hz: 4.9, effect: 'Induces relaxation, meditation, deeper sleep', source: 'James Bare', category: 'Brainwave' },
  { id: 'rife-fear-absentmindedness-dizzines-19', name: 'Fear/Absentmindedness/Dizziness', hz: 5.8, effect: 'Fear, absentmindedness, dizziness.', source: 'Royal Rife', category: 'Rife' },
  { id: 'brainwave-fear--absentmindedness--dizzin-20', name: 'Fear, absentmindedness, dizziness', hz: 5.8, effect: 'Reduces fear, absentmindedness, dizziness', source: 'James Bare', category: 'Brainwave' },
  { id: 'bw-theta', name: 'Theta — Deep Meditation', hz: 6.0, effect: 'Deep meditation, memory consolidation, creativity', source: 'Brainwave research', category: 'Brainwave' },
  { id: 'organ-abdominal-22', name: 'Abdominal', hz: 6.0, effect: 'Resonance for Abdominal', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'organ-shoulders-23', name: 'Shoulders', hz: 6.0, effect: 'Resonance for Shoulders', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'organ-lungs-24', name: 'Lungs', hz: 6.0, effect: 'Resonance for Lungs', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'rife-unwillingness-to-work-25', name: 'Unwillingness to work', hz: 6.0, effect: 'Motivation', source: 'James Bare', category: 'Rife' },
  { id: 'rife-anger-irritibility-26', name: 'Anger/Irritibility', hz: 6.3, effect: 'Anger and irritibility.', source: 'Royal Rife', category: 'Rife' },
  { id: 'brainwave-anger-and-irritability-27', name: 'Anger and irritability', hz: 6.3, effect: 'Reduces anger and irritability', source: 'Rife/Stafford', category: 'Brainwave' },
  { id: 'rife-muscle-28', name: 'muscle', hz: 6.8, effect: 'Possible use for muscle spasms.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-muscle-spasms-29', name: 'Muscle spasms', hz: 6.8, effect: 'Muscle spasm treatment', source: 'James Bare', category: 'Rife' },
  { id: 'brainwave-brain-waves---theta-state-30', name: 'Brain Waves - Theta State', hz: 7.0, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'superhuman-stem-cell-activation-31', name: 'Stem Cell Activation', hz: 7.5, effect: 'MSC migration', source: 'PMC', category: 'Superhuman' },
  { id: 'brainwave-schumann-frequency-32', name: 'Schumann frequency', hz: 7.8, effect: 'Psychic healing experiments', source: 'James Bare', category: 'Brainwave' },
  { id: 'schumann-1', name: 'Schumann 1st', hz: 7.83, effect: 'Earth electromagnetic resonance, grounding, alpha-theta bridge', source: 'Schumann 1952', category: 'Schumann' },
  { id: 'super-vo2', name: 'VO2 Max Enhancement', hz: 7.83, effect: 'Cardiovascular efficiency, VO2 max, red blood cell production', source: 'Schumann / bioresonance', category: 'Superhuman' },
  { id: 'rife-schumann-resonance-35', name: 'Schumann Resonance', hz: 7.83, effect: 'Grounding, balance, connection to Earth, reduce stress, emotional stability', source: 'W.O. Schumann', category: 'Rife' },
  { id: 'organ-spinal-column-36', name: 'Spinal Column', hz: 8.0, effect: 'Resonance for Spinal Column', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'brainwave-brain-waves---alpha-state-37', name: 'Brain Waves - Alpha State', hz: 8.0, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'rife-kidney-38', name: 'kidney', hz: 9.2, effect: 'Balancing/correction of kidney meridian.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-kidney-meridian-balancing-39', name: 'Kidney meridian balancing', hz: 9.2, effect: 'Kidney meridian balancing', source: 'James Bare', category: 'Organ' },
  { id: 'rife-prostate-40', name: 'Prostate', hz: 9.4, effect: 'Major freq. used for Prostate problems.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-prostate-problems-41', name: 'Prostate problems', hz: 9.4, effect: 'Prostate problems treatment', source: 'James Bare', category: 'Organ' },
  { id: 'rife-facial-42', name: 'Facial', hz: 9.6, effect: 'Facial toning.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-facial-toning-43', name: 'Facial toning', hz: 9.6, effect: 'Facial toning', source: 'James Bare', category: 'Rife' },
  { id: 'bw-alpha', name: 'Alpha — Relaxed Focus', hz: 10.0, effect: 'Relaxed focus, stress reduction, learning state', source: 'Brainwave research', category: 'Brainwave' },
  { id: 'dna-pemf-10', name: 'PEMF DNA Repair 10Hz', hz: 10.0, effect: 'PEMF 10 Hz — stimulates DNA repair enzymes, reduces oxidative damage', source: 'PEMF research', category: 'DNA' },
  { id: 'super-mito', name: 'Mitochondrial Biogenesis', hz: 10.0, effect: 'Mitochondrial biogenesis, ATP production increase, cellular energy', source: 'PEMF research', category: 'Superhuman' },
  { id: 'org-brain', name: 'Brain Resonance', hz: 10.0, effect: 'Brain alpha resonance, neural synchrony, cognitive clarity', source: 'EEG / bioresonance', category: 'Organ' },
  { id: 'rife-human-body-resonance-48', name: 'Human Body Resonance', hz: 10.0, effect: 'Resonant frequency of human body', source: 'Reddit discussion (unverified)', category: 'Rife' },
  { id: 'superhuman-hgh-stimulation-49', name: 'HGH Stimulation', hz: 10.0, effect: 'GH release', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'rife-mental-50', name: 'mental', hz: 12.0, effect: 'To stimulate mental clarity.', source: 'Royal Rife', category: 'Rife' },
  { id: 'superhuman-superhuman-potential-51', name: 'Superhuman Potential', hz: 12.0, effect: 'Activate superhuman potential', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'brainwave-mental-clarity-52', name: 'Mental clarity', hz: 12.0, effect: 'Mental clarity', source: 'James Bare', category: 'Brainwave' },
  { id: 'brainwave-brain-waves---alpha-state-53', name: 'Brain Waves - Alpha State', hz: 13.0, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'brainwave-brain-waves---beta-state-54', name: 'Brain Waves - Beta State', hz: 14.0, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'schumann-2', name: 'Schumann 2nd', hz: 14.3, effect: 'Second Schumann harmonic, beta entrainment', source: 'Schumann 1952', category: 'Schumann' },
  { id: 'superhuman-stem-cell-activation-56', name: 'Stem Cell Activation', hz: 15.0, effect: 'MSC migration', source: 'PMC', category: 'Superhuman' },
  { id: 'dna-adey', name: 'Adey Window ELF', hz: 16.0, effect: 'Adey window — ELF frequency affecting calcium ion efflux and gene expression', source: 'W. Ross Adey', category: 'DNA' },
  { id: 'bw-beta', name: 'Beta — Active Cognition', hz: 18.0, effect: 'Active thinking, concentration, problem solving', source: 'Brainwave research', category: 'Brainwave' },
  { id: 'organ-human-eyeball-resonance-59', name: 'Human Eyeball Resonance', hz: 19.0, effect: 'Resonance frequency of human eyeball', source: 'Medium.com', category: 'Organ' },
  { id: 'schumann-3', name: 'Schumann 3rd', hz: 20.8, effect: 'Third Schumann harmonic', source: 'Schumann 1952', category: 'Schumann' },
  { id: 'super-bone', name: 'Bone Density / Healing', hz: 25.0, effect: 'Bone marrow stromal cell differentiation, bone repair and density', source: 'PEMF / PMC research', category: 'Superhuman' },
  { id: 'superhuman-bone-density-healing-62', name: 'Bone Density/Healing', hz: 25.0, effect: 'Promote bone marrow stromal cell differentiation, repair bone injury', source: 'PMC', category: 'Superhuman' },
  { id: 'schumann-4', name: 'Schumann 4th', hz: 27.3, effect: 'Fourth Schumann harmonic', source: 'Schumann 1952', category: 'Schumann' },
  { id: 'super-muscle2', name: 'Muscle Fiber Hypertrophy', hz: 30.0, effect: 'Muscle hypertrophy signaling, mTOR pathway activation', source: 'PEMF / bioresonance', category: 'Superhuman' },
  { id: 'super-stem', name: 'Stem Cell Activation', hz: 30.0, effect: 'Mesenchymal stem cell migration and differentiation', source: 'PEMF / PMC research', category: 'Superhuman' },
  { id: 'organ-head-66', name: 'Head', hz: 30.0, effect: 'Resonance for Head', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'brainwave-brain-waves---beta-state-67', name: 'Brain Waves - Beta State', hz: 30.0, effect: 'Brainwave entrainment', source: 'Rife', category: 'Brainwave' },
  { id: 'org-pituitary', name: 'Pituitary Resonance', hz: 31.3, effect: 'Pituitary stimulation, master hormone gland activation', source: 'Bioresonance / frequency medicine', category: 'Organ' },
  { id: 'superhuman-hgh-stimulation-69', name: 'HGH Stimulation', hz: 31.3, effect: 'Pituitary stimulation, HGH release', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'superhuman-superhuman-potential-70', name: 'Superhuman Potential', hz: 33.0, effect: 'Activate superhuman potential', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'schumann-5', name: 'Schumann 5th', hz: 33.8, effect: 'Fifth Schumann harmonic, gamma bridge', source: 'Schumann 1952', category: 'Schumann' },
  { id: 'gariaev-40', name: 'Gariaev Coherence Carrier', hz: 40.0, effect: 'Gamma coherence carrier used in Gariaev wave genetics protocols', source: 'Peter Gariaev', category: 'WaveGenetics' },
  { id: 'bw-gamma', name: 'Gamma — Peak Cognition', hz: 40.0, effect: 'Peak cognitive performance, memory binding, consciousness', source: 'Brainwave research / MIT', category: 'Brainwave' },
  { id: 'super-neuro', name: 'Neuroplasticity BDNF', hz: 40.0, effect: 'BDNF upregulation, neuroplasticity, synaptic strengthening', source: 'MIT / Iaccarino 2016', category: 'Superhuman' },
  { id: 'superhuman-neuroplasticity-bdnf-75', name: 'Neuroplasticity/BDNF', hz: 40.0, effect: 'Brain function, synaptic potentiation, Alzheimer\'s', source: 'Various (MIT, PMC)', category: 'Superhuman' },
  { id: 'superhuman-stem-cell-activation-76', name: 'Stem Cell Activation', hz: 40.0, effect: 'SH-SY5Y Cells Growth', source: 'PMC', category: 'Superhuman' },
  { id: 'superhuman-cognitive-clarity-77', name: 'Cognitive Clarity', hz: 40.0, effect: 'Boost focus, clarity & energy', source: 'Various (Instagram, YouTube)', category: 'Superhuman' },
  { id: 'organ-hands-and-arms-78', name: 'Hands and arms', hz: 45.0, effect: 'Resonance for Hands and arms', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'dna-pemf-50', name: 'PEMF DNA Repair 50Hz', hz: 50.0, effect: 'PEMF 50 Hz — promotes DNA double-strand break repair', source: 'PEMF research', category: 'DNA' },
  { id: 'superhuman-stem-cell-activation-80', name: 'Stem Cell Activation', hz: 50.0, effect: 'MSC migration', source: 'PMC', category: 'Superhuman' },
  { id: 'superhuman-bone-density-healing-81', name: 'Bone Density/Healing', hz: 50.0, effect: 'Promote bone marrow stromal cell differentiation, repair bone injury', source: 'PMC', category: 'Superhuman' },
  { id: 'rife-disease-onset-82', name: 'Disease Onset', hz: 58.0, effect: 'Frequency where disease starts', source: 'Health and Bass', category: 'Rife' },
  { id: 'organ-chest-wall-83', name: 'Chest Wall', hz: 60.0, effect: 'Resonance for Chest Wall', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'rife-healthy-human-body-84', name: 'Healthy Human Body', hz: 62.0, effect: 'Resonance of healthy human body', source: 'Health and Bass, Facebook', category: 'Rife' },
  { id: 'superhuman-mitochondrial-biogenesis-85', name: 'Mitochondrial Biogenesis', hz: 62.5, effect: 'Total and functional mitochondria number', source: 'K Krajnak', category: 'Superhuman' },
  { id: 'organ-psoriasis-86', name: 'Psoriasis', hz: 64.0, effect: 'Psoriasis treatment', source: 'Clark', category: 'Organ' },
  { id: 'organ-heart-87', name: 'Heart', hz: 67.0, effect: 'Emotional balance & heart health', source: 'Bioresonance', category: 'Organ' },
  { id: 'rife-healthy-human-body-88', name: 'Healthy Human Body', hz: 68.0, effect: 'Resonance of healthy human body', source: 'Health and Bass, Facebook', category: 'Rife' },
  { id: 'superhuman-stem-cell-activation-89', name: 'Stem Cell Activation', hz: 70.0, effect: 'MSC migration', source: 'PMC', category: 'Superhuman' },
  { id: 'rife-parasites-90', name: 'Parasites', hz: 72.0, effect: 'Parasite elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-nausea-and-abdominal-cramping-91', name: 'Nausea and abdominal cramping', hz: 72.0, effect: 'Relieves nausea and abdominal cramping', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-worms-92', name: 'Worms', hz: 72.0, effect: 'Worm elimination', source: 'Clark', category: 'Rife' },
  { id: 'organ-ocular-globe-93', name: 'Ocular globe', hz: 75.0, effect: 'Resonance for Ocular globe', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'rife-pain-94', name: 'pain', hz: 95.0, effect: 'Major freq used for pain, along with #3.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-parasites-95', name: 'Parasites', hz: 95.0, effect: 'Parasite elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-nausea-and-abdominal-cramping-96', name: 'Nausea and abdominal cramping', hz: 95.0, effect: 'Relieves nausea and abdominal cramping', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-psoriasis-97', name: 'Psoriasis', hz: 96.0, effect: 'Psoriasis treatment', source: 'Clark', category: 'Organ' },
  { id: 'rife-trauma-98', name: 'Trauma', hz: 96.0, effect: 'Trauma relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-worms-99', name: 'Worms', hz: 96.0, effect: 'Worm elimination', source: 'Clark', category: 'Rife' },
  { id: 'bw-gamma-high', name: 'High Gamma — Hyper Cognition', hz: 100.0, effect: 'Hyper-cognition, transcendent states, advanced neuroplasticity', source: 'Brainwave research', category: 'Brainwave' },
  { id: 'rife-elf-101', name: 'ELF', hz: 100.0, effect: 'DNA integrity, DNA strand breaks', source: 'CT Mihai', category: 'Rife' },
  { id: 'rife-round-worms-102', name: 'Round Worms', hz: 104.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-psoriasis-103', name: 'Psoriasis', hz: 104.0, effect: 'Psoriasis treatment', source: 'Clark', category: 'Organ' },
  { id: 'org-stomach', name: 'Stomach Resonance', hz: 110.0, effect: 'Gastric function, digestive resonance, acid balance', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'rife-healing-frequency-105', name: 'Healing Frequency', hz: 110.0, effect: 'Mental clarity, grounding energy, emotional healing, focus, alleviate anxiety', source: 'Unknown', category: 'Rife' },
  { id: 'organ-stomach-106', name: 'Stomach', hz: 110.0, effect: 'Digestion & stomach wellness', source: 'Bioresonance', category: 'Organ' },
  { id: 'super-hgh', name: 'HGH Stimulation 111Hz', hz: 111.0, effect: 'Pituitary stimulation, human growth hormone release, cell regeneration', source: 'Various / Dr. Rife tradition', category: 'Superhuman' },
  { id: 'rife-angel-108', name: 'Angel', hz: 111.0, effect: 'New beginnings, spiritual awakening', source: 'Unknown', category: 'Rife' },
  { id: 'superhuman-hgh-stimulation-109', name: 'HGH Stimulation', hz: 111.0, effect: 'Pituitary stimulation, HGH release', source: 'Various (YouTube, Apple Music)', category: 'Superhuman' },
  { id: 'organ-psoriasis-110', name: 'Psoriasis', hz: 112.0, effect: 'Psoriasis treatment', source: 'Clark', category: 'Organ' },
  { id: 'organ-pancreas-111', name: 'Pancreas', hz: 117.0, effect: 'Insulin & blood sugar regulation', source: 'Bioresonance', category: 'Organ' },
  { id: 'org-pancreas', name: 'Pancreas Resonance', hz: 117.3, effect: 'Pancreatic function, insulin regulation, digestive enzyme production', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-pancreas-113', name: 'Pancreas', hz: 117.3, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-parasites-114', name: 'Parasites', hz: 120.0, effect: 'Parasite elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-fatigue-115', name: 'Fatigue', hz: 120.0, effect: 'Fatigue relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-tetanus-116', name: 'Tetanus', hz: 120.0, effect: 'Tetanus treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-rabies-117', name: 'Rabies', hz: 120.0, effect: 'Rabies treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-rhinitis-118', name: 'Rhinitis', hz: 120.0, effect: 'Rhinitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-ring-worm-119', name: 'Ring worm', hz: 120.0, effect: 'Ring worm treatment', source: 'Rife', category: 'Rife' },
  { id: 'brainwave-sciatica--nerve-inflammation-120', name: 'Sciatica, nerve inflammation', hz: 120.0, effect: 'Sciatica relief', source: 'Rife', category: 'Brainwave' },
  { id: 'rife-shell-shock-121', name: 'Shell Shock', hz: 120.0, effect: 'Shell Shock treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-sinus-disorders-122', name: 'Sinus disorders', hz: 120.0, effect: 'Sinus disorder treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-sleeping-sickness-123', name: 'Sleeping sickness', hz: 120.0, effect: 'Sleeping sickness treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-worms--parasites-124', name: 'Worms, Parasites', hz: 120.0, effect: 'Worms, Parasites elimination', source: 'Rife', category: 'Rife' },
  { id: 'superhuman-mitochondrial-biogenesis-125', name: 'Mitochondrial Biogenesis', hz: 125.0, effect: 'Total and functional mitochondria number', source: 'K Krajnak', category: 'Superhuman' },
  { id: 'rife-earth-126', name: 'Earth', hz: 126.22, effect: 'Stability, grounding', source: 'Unknown', category: 'Rife' },
  { id: 'rife-molecular-change-127', name: 'Molecular Change', hz: 128.0, effect: 'Enables molecular change during meditation/sleep', source: 'Reddit discussion (unverified)', category: 'Rife' },
  { id: 'rife-worms-128', name: 'Worms', hz: 128.0, effect: 'Worm elimination', source: 'Clark', category: 'Rife' },
  { id: 'rife-mercury-129', name: 'Mercury', hz: 141.27, effect: 'Communication, intellect', source: 'Unknown', category: 'Rife' },
  { id: 'rife-flukes-130', name: 'Flukes', hz: 143.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-headaches-131', name: 'Headaches', hz: 144.0, effect: 'Headache relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-mars-132', name: 'Mars', hz: 144.72, effect: 'Action, energy', source: 'Unknown', category: 'Rife' },
  { id: 'rife-saturn-133', name: 'Saturn', hz: 147.85, effect: 'Discipline, structure', source: 'Unknown', category: 'Rife' },
  { id: 'super-muscle', name: 'Type IIX Muscle Activation', hz: 150.0, effect: 'Fast-twitch Type IIX muscle fiber recruitment and growth stimulation', source: 'Neuromuscular research', category: 'Superhuman' },
  { id: 'organ-maxilla-135', name: 'Maxilla', hz: 150.0, effect: 'Resonance for Maxilla', source: 'Duarte & Pereira', category: 'Organ' },
  { id: 'rife-headaches-136', name: 'headaches', hz: 160.0, effect: 'Use for very rapid relief from headaches.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-gall-bladder-137', name: 'Gall Bladder', hz: 164.3, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-hepatitis-c-138', name: 'Hepatitis C', hz: 166.0, effect: 'Hepatitis C elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'superhuman-muscle-fiber-recruitment-chara-139', name: 'Muscle Fiber Recruitment Characteristics in Traine', hz: 170.0, effect: 'Muscle fiber activation', source: 'Matsumoto et al.', category: 'Superhuman' },
  { id: 'sol-174', name: '174 Hz — Foundation', hz: 174.0, effect: 'Pain reduction, foundation frequency, anesthetic effect', source: 'Solfeggio tradition', category: 'Solfeggio' },
  { id: 'solfeggio-solfeggio-141', name: 'Solfeggio', hz: 174.0, effect: 'Pain relief, relaxation, reducing physical and emotional tension, foundation, security, stability', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'org-colon', name: 'Colon Resonance', hz: 176.0, effect: 'Colon motility, gut microbiome support, elimination', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-colon-143', name: 'Colon', hz: 176.0, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-jupiter-144', name: 'Jupiter', hz: 183.58, effect: 'Abundance, expansion', source: 'Unknown', category: 'Rife' },
  { id: 'rife-nausea-and-abdominal-cramping-145', name: 'Nausea and abdominal cramping', hz: 190.0, effect: 'Relieves nausea and abdominal cramping', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-bladder-146', name: 'Bladder', hz: 192.0, effect: 'Urinary health', source: 'Bioresonance', category: 'Organ' },
  { id: 'rife-trauma-147', name: 'Trauma', hz: 192.0, effect: 'Trauma relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-uranus-148', name: 'Uranus', hz: 207.36, effect: 'Innovation, change', source: 'Unknown', category: 'Rife' },
  { id: 'rife-neptune-149', name: 'Neptune', hz: 211.44, effect: 'Intuition, dreams', source: 'Unknown', category: 'Rife' },
  { id: 'org-lung', name: 'Lung Resonance', hz: 220.0, effect: 'Pulmonary resonance, bronchial dilation, oxygen uptake', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-lungs-151', name: 'Lungs', hz: 220.0, effect: 'Respiratory strength & lung function', source: 'Bioresonance', category: 'Organ' },
  { id: 'rife-venus-152', name: 'Venus', hz: 221.23, effect: 'Love, harmony', source: 'Unknown', category: 'Rife' },
  { id: 'rife-angel-153', name: 'Angel', hz: 222.0, effect: 'Balance and harmony in relationships', source: 'Unknown', category: 'Rife' },
  { id: 'rife-hepatitis-c-154', name: 'Hepatitis C', hz: 224.0, effect: 'Hepatitis C elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-stroke-155', name: 'stroke', hz: 230.0, effect: 'Major freq. used for stroke along with # 78.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-kidneys-156', name: 'Kidneys', hz: 248.0, effect: 'Kidney support', source: 'Clark', category: 'Organ' },
  { id: 'rife-flukes-157', name: 'Flukes', hz: 275.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'superhuman-mitochondrial-biogenesis-158', name: 'Mitochondrial Biogenesis', hz: 280.0, effect: 'Cellular regeneration, energy production', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'organ-intestines-159', name: 'Intestines', hz: 281.0, effect: 'Gut health & digestion', source: 'Bioresonance', category: 'Organ' },
  { id: 'sol-285', name: '285 Hz — Tissue Repair', hz: 285.0, effect: 'Tissue regeneration, cellular repair, immune boost', source: 'Solfeggio tradition', category: 'Solfeggio' },
  { id: 'super-hgh2', name: 'HGH Stimulation 285Hz', hz: 285.0, effect: 'HGH and IGF-1 stimulation, tissue repair and growth', source: 'Solfeggio / bioresonance', category: 'Superhuman' },
  { id: 'solfeggio-solfeggio-162', name: 'Solfeggio', hz: 285.0, effect: 'Cellular healing and regeneration, emotional balance, peace of mind, healing tissues', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'solfeggio-solfeggio-healing-163', name: 'Solfeggio Healing', hz: 285.0, effect: 'Tissue healing and regeneration', source: 'Various (YouTube, Spotify, Linde Estheti', category: 'Solfeggio' },
  { id: 'solfeggio-immune-system-boost-164', name: 'Immune System Boost', hz: 285.0, effect: 'Heals and regenerates tissues, immune system enhancer', source: 'Various (YouTube, Spotify)', category: 'Solfeggio' },
  { id: 'organ-fat-cells-165', name: 'Fat Cells', hz: 295.8, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-lumbago-166', name: 'Lumbago', hz: 300.0, effect: 'Lumbago relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-stiff-muscles-167', name: 'Stiff muscles', hz: 300.0, effect: 'Stiff muscle relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-trauma-168', name: 'Trauma', hz: 300.0, effect: 'Trauma relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-sedation-or-pain-relief-169', name: 'Sedation or pain relief', hz: 304.0, effect: 'Sedation or pain relief', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-nausea-and-abdominal-cramping-170', name: 'Nausea and abdominal cramping', hz: 304.0, effect: 'Relieves nausea and abdominal cramping', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-blood-pressure-171', name: 'Blood pressure', hz: 304.0, effect: 'Blood pressure regulation', source: 'Clark', category: 'Rife' },
  { id: 'rife-headaches-172', name: 'Headaches', hz: 304.0, effect: 'Headache relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-sedation-and-pain-relief-173', name: 'Sedation and pain relief', hz: 304.0, effect: 'Sedation and pain relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-brain-174', name: 'Brain', hz: 315.8, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-hepatitis-c-175', name: 'Hepatitis C', hz: 317.0, effect: 'Hepatitis C elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'org-liver', name: 'Liver Resonance', hz: 317.83, effect: 'Liver detoxification support, hepatic cell resonance', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-liver-177', name: 'Liver', hz: 317.83, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'org-kidney', name: 'Kidney Resonance', hz: 319.88, effect: 'Kidney function support, renal cell resonance', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-kidneys-179', name: 'Kidneys', hz: 319.88, effect: 'Kidney detox & filtration support', source: 'Bioresonance', category: 'Organ' },
  { id: 'org-blood', name: 'Blood Resonance', hz: 321.9, effect: 'Blood cell resonance, hemoglobin optimization, circulation', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-blood-181', name: 'Blood', hz: 321.9, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'organ-muscles-182', name: 'Muscles', hz: 324.0, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-stiff-muscles-183', name: 'Stiff muscles', hz: 328.0, effect: 'Stiff muscle relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-round-worms-184', name: 'Round Worms', hz: 332.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'super-testosterone', name: 'Testosterone Stimulation', hz: 333.0, effect: 'Anabolic hormone stimulation, testosterone and testosterone-related pathways', source: 'Bioresonance / frequency medicine', category: 'Superhuman' },
  { id: 'rife-tesla-186', name: 'Tesla', hz: 333.0, effect: 'Balance and harmony, spiritual awareness, intuition', source: 'Nikola Tesla', category: 'Rife' },
  { id: 'superhuman-superhuman-potential-187', name: 'Superhuman Potential', hz: 333.0, effect: 'Activate superhuman potential', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'organ-eyesight-sharpening-188', name: 'Eyesight sharpening', hz: 350.0, effect: 'Sharpen eyesight', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'organ-spleen-189', name: 'Spleen', hz: 352.0, effect: 'Immune system support', source: 'Bioresonance', category: 'Organ' },
  { id: 'organ-eyesight-sharpening-190', name: 'Eyesight sharpening', hz: 360.0, effect: 'Sharpen eyesight', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'sol-ut', name: 'UT — Liberation', hz: 396.0, effect: 'Liberating guilt and fear, root chakra activation', source: 'Puleo/Horowitz', category: 'Solfeggio' },
  { id: 'solfeggio-ut-solfeggio-192', name: 'UT Solfeggio', hz: 396.0, effect: 'Liberating guilt and fear, positive change, emotional stability', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'rife-tetanus-193', name: 'Tetanus', hz: 400.0, effect: 'Tetanus treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-prostate-194', name: 'Prostate', hz: 408.0, effect: 'Prostate support', source: 'Clark', category: 'Organ' },
  { id: 'sol-re', name: 'RE — Undoing', hz: 417.0, effect: 'Undoing situations and facilitating change', source: 'Puleo/Horowitz', category: 'Solfeggio' },
  { id: 'solfeggio-re-solfeggio-196', name: 'RE Solfeggio', hz: 417.0, effect: 'Undoing situations, facilitating change, removing negative energy, creativity, problem-solving', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'org-bone-marrow', name: 'Bone Marrow Resonance', hz: 418.3, effect: 'Bone marrow stimulation, red blood cell production', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'organ-bone-198', name: 'Bone', hz: 418.3, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'superhuman-bone-healing-199', name: 'Bone Healing', hz: 418.3, effect: 'Skeletal pain relief, heal bones faster', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'rife-cancer-200', name: 'Cancer', hz: 421.0, effect: 'Cancer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-round-worms-201', name: 'Round Worms', hz: 422.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-cancer-202', name: 'Cancer', hz: 423.0, effect: 'Cancer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-fatigue-203', name: 'Fatigue', hz: 424.0, effect: 'Fatigue relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-cancer-204', name: 'Cancer', hz: 425.0, effect: 'Cancer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-cancer-205', name: 'Cancer', hz: 427.0, effect: 'Cancer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-chlamydia-infections-206', name: 'Chlamydia infections', hz: 430.0, effect: 'Chlamydia elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-verdi-s-a-207', name: 'Verdi\'s A', hz: 432.0, effect: 'Overall well-being, healing', source: 'Giuseppe Verdi', category: 'Rife' },
  { id: 'solfeggio-solfeggio-concert-pitch-208', name: 'Solfeggio/Concert Pitch', hz: 432.0, effect: 'Promotes emotional well-being', source: 'Various sources', category: 'Solfeggio' },
  { id: 'rife-lyme-disease-209', name: 'Lyme Disease', hz: 432.0, effect: 'Lyme disease elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-cancer-210', name: 'Cancer', hz: 432.0, effect: 'Cancer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-lyme-211', name: 'Lyme', hz: 432.0, effect: 'Lyme treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-cancer-212', name: 'Cancer', hz: 434.0, effect: 'Cancer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-flukes-213', name: 'Flukes', hz: 435.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-kidneys-214', name: 'Kidneys', hz: 440.0, effect: 'Kidney support', source: 'Clark', category: 'Organ' },
  { id: 'rife-motion-sickness-215', name: 'Motion sickness', hz: 440.0, effect: 'Motion sickness relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-pancreas-216', name: 'Pancreas', hz: 440.0, effect: 'Pancreas support', source: 'Clark', category: 'Organ' },
  { id: 'rife-angel-217', name: 'Angel', hz: 444.0, effect: 'Protection and divine guidance', source: 'Unknown', category: 'Rife' },
  { id: 'brainwave-involuntary-tremors-218', name: 'Involuntary tremors', hz: 463.0, effect: 'Stopped involuntary tremors (brain tumors)', source: 'Rife/Stafford', category: 'Brainwave' },
  { id: 'rife-candida-219', name: 'Candida', hz: 464.0, effect: 'Candida treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-fatigue-220', name: 'Fatigue', hz: 464.0, effect: 'Fatigue relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-motion-sickness-221', name: 'Motion sickness', hz: 464.0, effect: 'Motion sickness relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-pancreas-222', name: 'Pancreas', hz: 464.0, effect: 'Pancreas support', source: 'Clark', category: 'Organ' },
  { id: 'rife-thrush-223', name: 'Thrush', hz: 464.0, effect: 'Thrush treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-fungal-224', name: 'fungal', hz: 465.0, effect: 'Major freq. used for fungal & yeast infection.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-candida-225', name: 'Candida', hz: 465.0, effect: 'Candida elimination', source: 'Rife', category: 'Rife' },
  { id: 'brainwave-involuntary-tremors-226', name: 'Involuntary tremors', hz: 466.0, effect: 'Stopped involuntary tremors (brain tumors)', source: 'Rife/Stafford', category: 'Brainwave' },
  { id: 'brainwave-involuntary-tremors-227', name: 'Involuntary tremors', hz: 470.0, effect: 'Stopped involuntary tremors (MS)', source: 'Rife/Stafford', category: 'Brainwave' },
  { id: 'rife-lyme-disease-228', name: 'Lyme disease', hz: 484.0, effect: 'Lyme disease elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'org-spleen', name: 'Spleen Resonance', hz: 492.0, effect: 'Spleen function, blood filtration, immune cell production', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'org-thymus', name: 'Thymus Resonance', hz: 492.8, effect: 'Thymus activation, T-cell production, immune system master gland', source: 'Bioresonance / Rife', category: 'Organ' },
  { id: 'organ-adrenals-231', name: 'Adrenals', hz: 492.8, effect: 'Organ resonance', source: 'Cosmic/Bioresonance', category: 'Organ' },
  { id: 'rife-bubonic-plague-232', name: 'Bubonic Plague', hz: 500.0, effect: 'Bubonic Plague elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-anthrax-233', name: 'Anthrax', hz: 500.0, effect: 'Anthrax treatment', source: 'Clark', category: 'Rife' },
  { id: 'superhuman-telomere-lengthening-234', name: 'Telomere Lengthening', hz: 502.0, effect: 'Lengthening of telomeres', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'rife-headaches-235', name: 'Headaches', hz: 520.0, effect: 'Headache relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-flukes-236', name: 'Flukes', hz: 524.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'sol-mi', name: 'MI — DNA Repair', hz: 528.0, effect: 'DNA repair, transformation, miracles (Gariaev confirmed)', source: 'Puleo/Horowitz/Gariaev', category: 'Solfeggio' },
  { id: 'super-telo', name: 'Telomere Lengthening', hz: 528.0, effect: 'Telomerase activation, telomere lengthening, anti-aging at DNA level', source: 'Horowitz / wave genetics', category: 'Superhuman' },
  { id: 'super-immune', name: 'Immune Enhancement', hz: 528.0, effect: 'Immune system enhancement, NK cell activation, cytokine regulation', source: 'Various / Solfeggio', category: 'Superhuman' },
  { id: 'org-dna-cell', name: 'DNA/Cell Resonance', hz: 528.0, effect: 'Cellular DNA resonance, repair and coherence', source: 'Gariaev / Horowitz', category: 'Organ' },
  { id: 'rife-mi-solfeggio-241', name: 'MI Solfeggio', hz: 528.0, effect: 'DNA repair, transformation, miracles, love, peace, harmony', source: 'Dr. Joseph Puleo, Dr. Leonard Horowitz', category: 'Rife' },
  { id: 'superhuman-testosterone-booster-242', name: 'Testosterone Booster', hz: 528.0, effect: 'Testosterone production', source: 'Various (Spotify, Apple Music, PubMed)', category: 'Superhuman' },
  { id: 'solfeggio-immune-system-boost-243', name: 'Immune System Boost', hz: 528.0, effect: 'Enhance immune system', source: 'Various (Spotify)', category: 'Solfeggio' },
  { id: 'dna-cytocine-244', name: 'Cytocine', hz: 537.8, effect: 'DNA resonance', source: 'Cosmic/Bioresonance', category: 'DNA' },
  { id: 'dna-thymine-245', name: 'Thymine', hz: 543.4, effect: 'DNA resonance', source: 'Cosmic/Bioresonance', category: 'DNA' },
  { id: 'dna-adenine-246', name: 'Adenine', hz: 544.4, effect: 'DNA resonance', source: 'Cosmic/Bioresonance', category: 'DNA' },
  { id: 'dna-guanine-247', name: 'Guanine', hz: 545.6, effect: 'DNA resonance', source: 'Cosmic/Bioresonance', category: 'DNA' },
  { id: 'rife-angel-248', name: 'Angel', hz: 555.0, effect: 'Transformation and adaptability', source: 'Unknown', category: 'Rife' },
  { id: 'rife-leprosy-249', name: 'Leprosy', hz: 600.0, effect: 'Major freq. used for Leprosy.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-motion-sickness-250', name: 'Motion sickness', hz: 600.0, effect: 'Motion sickness relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-pancreas-251', name: 'Pancreas', hz: 600.0, effect: 'Pancreas support', source: 'Clark', category: 'Organ' },
  { id: 'organ-erysipelas--skin-inflammation-252', name: 'Erysipelas (skin inflammation)', hz: 600.0, effect: 'Erysipelas treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-lyme-disease-253', name: 'Lyme disease', hz: 610.0, effect: 'Lyme disease elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-chlamydia-infections-254', name: 'Chlamydia infections', hz: 620.0, effect: 'Chlamydia elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-motion-sickness-255', name: 'Motion sickness', hz: 624.0, effect: 'Motion sickness relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-pancreas-256', name: 'Pancreas', hz: 624.0, effect: 'Pancreas support', source: 'Clark', category: 'Organ' },
  { id: 'rife-sexual-diseases-257', name: 'Sexual diseases', hz: 625.0, effect: 'Sexual diseases treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-syphilis-258', name: 'Syphilis', hz: 625.0, effect: 'Syphilis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-he-ne-laser-259', name: 'He-Ne Laser', hz: 632.8, effect: 'DNA wave genetics, phantom DNA effect', source: 'Peter Gariaev', category: 'Rife' },
  { id: 'sol-fa', name: 'FA — Relationships', hz: 639.0, effect: 'Connecting, relationships, heart resonance', source: 'Puleo/Horowitz', category: 'Solfeggio' },
  { id: 'solfeggio-fa-solfeggio-261', name: 'FA Solfeggio', hz: 639.0, effect: 'Connecting, relationships, communication, harmony', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'solfeggio-cardiovascular-enhancement-262', name: 'Cardiovascular Enhancement', hz: 639.0, effect: 'Improve circulation, support heart strength', source: 'Various (YouTube, Spotify)', category: 'Solfeggio' },
  { id: 'superhuman-superhuman-potential-263', name: 'Superhuman Potential', hz: 639.0, effect: 'Activate superhuman potential', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'rife-motion-sickness-264', name: 'Motion sickness', hz: 648.0, effect: 'Motion sickness relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-pancreas-265', name: 'Pancreas', hz: 648.0, effect: 'Pancreas support', source: 'Clark', category: 'Organ' },
  { id: 'rife-syphilis-266', name: 'Syphilis', hz: 650.0, effect: 'Syphilis elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-flukes-267', name: 'Flukes', hz: 651.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-gonorrhea-268', name: 'Gonorrhea', hz: 660.0, effect: 'Gonorrhea elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-epstein-barr-virus-269', name: 'Epstein Barr virus', hz: 660.0, effect: 'Epstein Barr virus elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-treponema-270', name: 'Treponema', hz: 660.0, effect: 'Treponema treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-pelvic--disorders-271', name: 'Pelvic, disorders', hz: 660.0, effect: 'Pelvic disorder treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-sexual-diseases-272', name: 'Sexual diseases', hz: 660.0, effect: 'Sexual diseases treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-herpes-simplex-i-273', name: 'Herpes simplex I', hz: 662.0, effect: 'Herpes simplex I treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-emotional-ties-to-diseases-274', name: 'Emotional ties to diseases', hz: 664.0, effect: 'Emotional release', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-bacterial-infections-275', name: 'Bacterial infections', hz: 664.0, effect: 'Bacterial infection treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-fatigue-276', name: 'Fatigue', hz: 664.0, effect: 'Fatigue relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-herpes-simplex-i-277', name: 'Herpes simplex I', hz: 664.0, effect: 'Herpes simplex I treatment', source: 'Clark', category: 'Rife' },
  { id: 'organ-prostate-278', name: 'Prostate', hz: 664.0, effect: 'Prostate support', source: 'Clark', category: 'Organ' },
  { id: 'organ-stomach-279', name: 'Stomach', hz: 664.0, effect: 'Stomach support', source: 'Clark', category: 'Organ' },
  { id: 'rife-ulcers-280', name: 'Ulcers', hz: 664.0, effect: 'Ulcer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-angel-281', name: 'Angel', hz: 666.0, effect: 'Balance and spiritual integration', source: 'Unknown', category: 'Rife' },
  { id: 'rife-leukemia-282', name: 'Leukemia', hz: 666.0, effect: 'Major freq. used for Leukemia.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-herpes-simplex-i-283', name: 'Herpes simplex I', hz: 666.0, effect: 'Herpes simplex I treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-h--pylori-284', name: 'H. Pylori', hz: 676.0, effect: 'H. Pylori elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-heliobacterium-pylori-285', name: 'Heliobacterium pylori', hz: 676.0, effect: 'Heliobacterium pylori treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-blood-clots-286', name: 'Blood clots', hz: 685.0, effect: 'Blood clot treatment', source: 'James Bare', category: 'Rife' },
  { id: 'rife-round-worms-287', name: 'Round Worms', hz: 688.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-leukemia-288', name: 'Leukemia', hz: 690.0, effect: 'Major freq. used for Leukemia.', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-lyme-disease-289', name: 'Lyme disease', hz: 690.0, effect: 'Lyme disease elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-bacteria-290', name: 'Bacteria', hz: 690.0, effect: 'Bacteria treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-typhoid-291', name: 'Typhoid', hz: 690.0, effect: 'Typhoid treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-gonorrhea-292', name: 'Gonorrhea', hz: 712.0, effect: 'Gonorrhea treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-round-worms-293', name: 'Round Worms', hz: 721.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-staphylococcus-294', name: 'Staphylococcus', hz: 725.0, effect: 'Staphylococcus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-leukemia-295', name: 'Leukemia', hz: 727.0, effect: 'Major freq. used for Leukemia & Staphlococci.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-general-organ-296', name: 'General Organ', hz: 727.0, effect: 'Distended organs', source: 'Rife', category: 'Organ' },
  { id: 'rife-staphylococci-297', name: 'Staphylococci', hz: 727.0, effect: 'Staphylococci elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-general-overall-system-tonic-298', name: 'General Overall System Tonic', hz: 727.0, effect: 'General tonic', source: 'Rife', category: 'Rife' },
  { id: 'rife-catarrh--mucous-299', name: 'Catarrh (mucous)', hz: 727.0, effect: 'Catarrh relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-raynaud-s-disease-300', name: 'Raynaud\'s disease', hz: 727.0, effect: 'Raynaud\'s disease treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-cancer-cell---conidium-head-301', name: 'Cancer cell ("conidium head")', hz: 728.0, effect: 'Cancer cell disintegration', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-epstein-barr-virus-302', name: 'Epstein Barr virus', hz: 728.0, effect: 'Epstein Barr virus elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-cancer-cells---conidium-head-303', name: 'Cancer cells ("conidium head")', hz: 728.0, effect: 'Cancer cell disintegration', source: 'Clark', category: 'Rife' },
  { id: 'rife-arthritis-304', name: 'Arthritis', hz: 728.0, effect: 'Arthritis relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-blood-pressure-305', name: 'Blood pressure', hz: 728.0, effect: 'Blood pressure regulation', source: 'Clark', category: 'Rife' },
  { id: 'organ-cataract-306', name: 'Cataract', hz: 728.0, effect: 'Cataract treatment', source: 'Clark', category: 'Organ' },
  { id: 'rife-catarrh-307', name: 'Catarrh', hz: 728.0, effect: 'Catarrh relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-eye-disorders-308', name: 'Eye disorders', hz: 728.0, effect: 'Eye disorder treatment', source: 'Clark', category: 'Organ' },
  { id: 'rife-gallstones-309', name: 'Gallstones', hz: 728.0, effect: 'Gallstone treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-lumbago-310', name: 'Lumbago', hz: 728.0, effect: 'Lumbago relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-pharyngitis-311', name: 'Pharyngitis', hz: 728.0, effect: 'Pharyngitis relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-prostate-312', name: 'Prostate', hz: 728.0, effect: 'Prostate support', source: 'Clark', category: 'Organ' },
  { id: 'rife-staphylococci-313', name: 'Staphylococci', hz: 728.0, effect: 'Staphylococci treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-stiff-muscles-314', name: 'Stiff muscles', hz: 728.0, effect: 'Stiff muscle relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-stomach-315', name: 'Stomach', hz: 728.0, effect: 'Stomach support', source: 'Clark', category: 'Organ' },
  { id: 'rife-tinnitus-316', name: 'Tinnitus', hz: 728.0, effect: 'Tinnitus relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-coughing--colds-317', name: 'Coughing, Colds', hz: 728.0, effect: 'Coughing, colds treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-staphylococcus-318', name: 'Staphylococcus', hz: 730.0, effect: 'Staphylococcus treatment', source: 'Rife', category: 'Rife' },
  { id: 'sol-sol', name: 'SOL — Intuition', hz: 741.0, effect: 'Awakening intuition, detoxification, pineal activation', source: 'Puleo/Horowitz', category: 'Solfeggio' },
  { id: 'solfeggio-sol-solfeggio-320', name: 'SOL Solfeggio', hz: 741.0, effect: 'Detox, expression, solutions, cleansing, releasing negative energy, inner peace, clarity', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'organ-thyroid-321', name: 'Thyroid', hz: 741.0, effect: 'Metabolism & hormonal balance', source: 'Bioresonance', category: 'Organ' },
  { id: 'solfeggio-immune-system-boost-322', name: 'Immune System Boost', hz: 741.0, effect: 'Cleanse infections, dissolve toxins, boost immune system', source: 'Various (YouTube)', category: 'Solfeggio' },
  { id: 'rife-basal-cell-skin-carcinoma-323', name: 'Basal Cell Skin Carcinoma', hz: 760.0, effect: 'Basal cell skin carcinoma elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-trauma-324', name: 'Trauma', hz: 760.0, effect: 'Trauma relief', source: 'Clark', category: 'Rife' },
  { id: 'org-thyroid', name: 'Thyroid Resonance', hz: 763.0, effect: 'Thyroid function, metabolic rate regulation, T3/T4 balance', source: 'Bioresonance therapy', category: 'Organ' },
  { id: 'rife-flukes-326', name: 'Flukes', hz: 763.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-emotional-ties-to-diseases-327', name: 'Emotional ties to diseases', hz: 764.0, effect: 'Emotional release', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-pneumonia-328', name: 'Pneumonia', hz: 770.0, effect: 'Pneumonia treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-diphtheria-329', name: 'Diphtheria', hz: 776.0, effect: 'Diphtheria elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-pharyngitis-330', name: 'Pharyngitis', hz: 776.0, effect: 'Pharyngitis relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-pneumococci-331', name: 'Pneumococci', hz: 776.0, effect: 'Pneumococci treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-ulcers-332', name: 'Ulcers', hz: 776.0, effect: 'Ulcer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-pneumonia-333', name: 'Pneumonia', hz: 776.0, effect: 'Pneumonia treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-angel-334', name: 'Angel', hz: 777.0, effect: 'Spiritual awareness and divine alignment', source: 'Unknown', category: 'Rife' },
  { id: 'rife-spiritual-awakening-335', name: 'Spiritual Awakening', hz: 777.0, effect: 'Spiritual awakening', source: 'Meditation Music Library', category: 'Rife' },
  { id: 'rife-pneumonia-336', name: 'Pneumonia', hz: 780.0, effect: 'Pneumonia treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-strepto-thrix--fungi-337', name: 'Strepto-thrix (Fungi)', hz: 781.0, effect: 'Strepto-thrix (Fungi) treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-psoriasis-338', name: 'Psoriasis', hz: 784.0, effect: 'Psoriasis treatment', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'rife-arthritis-339', name: 'Arthritis', hz: 784.0, effect: 'Arthritis relief', source: 'Clark', category: 'Rife' },
  { id: 'organ-cataract-340', name: 'Cataract', hz: 784.0, effect: 'Cataract treatment', source: 'Clark', category: 'Organ' },
  { id: 'rife-pharyngitis-341', name: 'Pharyngitis', hz: 784.0, effect: 'Pharyngitis relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-rubella-342', name: 'Rubella', hz: 784.0, effect: 'Rubella treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-rubeola-343', name: 'Rubeola', hz: 784.0, effect: 'Rubeola treatment', source: 'Clark', category: 'Rife' },
  { id: 'organ-stomach-344', name: 'Stomach', hz: 784.0, effect: 'Stomach support', source: 'Clark', category: 'Organ' },
  { id: 'rife-streptothrix-345', name: 'Streptothrix', hz: 784.0, effect: 'Streptothrix treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-tinnitus-346', name: 'Tinnitus', hz: 784.0, effect: 'Tinnitus relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-ulcers-347', name: 'Ulcers', hz: 784.0, effect: 'Ulcer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-herpes-simplex-i-348', name: 'Herpes simplex I', hz: 785.0, effect: 'Herpes simplex I treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-herpes-simplex-i-349', name: 'Herpes simplex I', hz: 786.0, effect: 'Herpes simplex I treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-universal-remedy-350', name: 'Universal Remedy', hz: 787.0, effect: 'General healing', source: 'Royal Raymond Rife', category: 'Rife' },
  { id: 'organ-general-organ-351', name: 'General Organ', hz: 787.0, effect: 'Distended organs', source: 'Rife', category: 'Organ' },
  { id: 'rife-rubella-352', name: 'Rubella', hz: 787.0, effect: 'Rubella elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-epstein-barr-virus-353', name: 'Epstein Barr virus', hz: 787.0, effect: 'Epstein Barr virus elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-general-overall-system-tonic-354', name: 'General Overall System Tonic', hz: 787.0, effect: 'General tonic', source: 'Rife', category: 'Rife' },
  { id: 'rife-candida-albicans-355', name: 'Candida albicans', hz: 787.0, effect: 'Candida treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-eye--swollen-lid-356', name: 'Eye, swollen lid', hz: 787.0, effect: 'Eye, swollen lid treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-lyme-disease-357', name: 'Lyme disease', hz: 790.0, effect: 'Lyme disease elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-strepto-thrix--fungi-358', name: 'Strepto-thrix (Fungi)', hz: 790.0, effect: 'Strepto-thrix (Fungi) treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-e-coli--tuberculosis-rod-359', name: 'E-Coli; Tuberculosis Rod', hz: 799.0, effect: 'E-Coli; Tuberculosis Rod treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-tuberculosis-360', name: 'Tuberculosis', hz: 800.0, effect: 'Tuberculosis elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-arthritis-361', name: 'Arthritis', hz: 800.0, effect: 'Arthritis relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-bacillus-coli-rod-form-362', name: 'Bacillus coli rod form', hz: 800.0, effect: 'Bacillus coli rod form treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-bacterial-infections-363', name: 'Bacterial infections', hz: 800.0, effect: 'Bacterial infection treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-catarrh-364', name: 'Catarrh', hz: 800.0, effect: 'Catarrh relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-flu-virus-365', name: 'Flu virus', hz: 800.0, effect: 'Flu virus treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-lumbago-366', name: 'Lumbago', hz: 800.0, effect: 'Lumbago relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-pharyngitis-367', name: 'Pharyngitis', hz: 800.0, effect: 'Pharyngitis relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-shingles--herpes-zoster-368', name: 'Shingles (herpes zoster)', hz: 800.0, effect: 'Shingles relief', source: 'Clark', category: 'Rife' },
  { id: 'rife-ulcers-369', name: 'Ulcers', hz: 800.0, effect: 'Ulcer treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-general-overall-system-tonic-370', name: 'General Overall System Tonic', hz: 800.0, effect: 'General tonic', source: 'Rife', category: 'Rife' },
  { id: 'rife-colic--stomach-and-colon-pain-371', name: 'Colic, stomach and colon pain', hz: 800.0, effect: 'Colic relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-colitis--mucous-catarrh-of-col-372', name: 'Colitis, mucous catarrh of colon', hz: 800.0, effect: 'Colitis relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-constipation-373', name: 'Constipation', hz: 800.0, effect: 'Constipation relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-distended-stomach-374', name: 'Distended stomach', hz: 800.0, effect: 'Distended stomach treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-dysmenorrhea---painful-menses-375', name: 'Dysmenorrhea, (painful menses)', hz: 800.0, effect: 'Dysmenorrhea relief', source: 'Rife', category: 'Rife' },
  { id: 'organ-eustachian-tube--from-nose-to-376', name: 'Eustachian tube (from nose to ear)', hz: 800.0, effect: 'Eustachian tube support', source: 'Rife', category: 'Organ' },
  { id: 'rife-gums--inflamed-377', name: 'Gums, inflamed', hz: 800.0, effect: 'Gums, inflamed treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-hemorrhage-378', name: 'Hemorrhage', hz: 800.0, effect: 'Hemorrhage treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-hemorrhoids-379', name: 'Hemorrhoids', hz: 800.0, effect: 'Hemorrhoids treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-hepatitis--liver-inflammation-380', name: 'Hepatitis, liver inflammation', hz: 800.0, effect: 'Hepatitis, liver inflammation treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-ileocolitis--colon-inflammatio-381', name: 'Ileocolitis, colon inflammation', hz: 800.0, effect: 'Ileocolitis relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-laxative--mild-382', name: 'Laxative, mild', hz: 800.0, effect: 'Laxative effect', source: 'Rife', category: 'Rife' },
  { id: 'rife-lupus-vulgaris-383', name: 'Lupus vulgaris', hz: 800.0, effect: 'Lupus vulgaris treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-moth-patches--urticaria-384', name: 'Moth patches, urticaria', hz: 800.0, effect: 'Moth patches, urticaria treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-orchitis--testis-inflammation-385', name: 'Orchitis, testis inflammation', hz: 800.0, effect: 'Orchitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-parasites-386', name: 'Parasites', hz: 800.0, effect: 'Parasite elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-poor-appetite-387', name: 'Poor appetite', hz: 800.0, effect: 'Poor appetite treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-skin-hemorrhages-388', name: 'Skin hemorrhages', hz: 800.0, effect: 'Skin hemorrhage treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-stomach-swelling-389', name: 'Stomach swelling', hz: 800.0, effect: 'Stomach swelling treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-thrombosis--heart-clot-390', name: 'Thrombosis, heart clot', hz: 800.0, effect: 'Thrombosis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-worms--parasites-391', name: 'Worms, Parasites', hz: 800.0, effect: 'Worms, Parasites elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-e--coli-392', name: 'E. Coli', hz: 802.0, effect: 'E. Coli elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-tuberculosis-rod-form-393', name: 'Tuberculosis rod form', hz: 803.0, effect: 'Tuberculosis rod form treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-herpes-simplex-ii-394', name: 'Herpes simplex II', hz: 804.0, effect: 'Herpes simplex II treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-e-coli--tuberculosis-rod-395', name: 'E-Coli; Tuberculosis Rod', hz: 804.0, effect: 'E-Coli; Tuberculosis Rod treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-herpes-simplex-ii-396', name: 'Herpes simplex II', hz: 807.0, effect: 'Herpes simplex II treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-herpes-simplex-ii-397', name: 'Herpes simplex II', hz: 818.0, effect: 'Herpes simplex II treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-fungus-ew-398', name: 'Fungus EW', hz: 823.0, effect: 'Fungus treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-herpes-simplex-ii-399', name: 'Herpes simplex II', hz: 825.0, effect: 'Herpes simplex II treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-fungus-ew-400', name: 'Fungus EW', hz: 829.0, effect: 'Fungus treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-hiv-401', name: 'HIV', hz: 829.0, effect: 'HIV treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-hiv-402', name: 'HIV', hz: 830.0, effect: 'HIV treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-bacterial-infections-403', name: 'Bacterial infections', hz: 832.0, effect: 'Bacterial infection treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-ulcers-404', name: 'Ulcers', hz: 832.0, effect: 'Ulcer treatment', source: 'Clark', category: 'Rife' },
  { id: 'sol-la', name: 'LA — Spiritual Order', hz: 852.0, effect: 'Returning to spiritual order, third eye activation', source: 'Puleo/Horowitz', category: 'Solfeggio' },
  { id: 'solfeggio-la-solfeggio-406', name: 'LA Solfeggio', hz: 852.0, effect: 'Awakening intuition, spiritual connection, inner strength, self-awareness', source: 'Dr. Joseph Puleo', category: 'Solfeggio' },
  { id: 'rife-flukes-407', name: 'Flukes', hz: 854.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-lyme-408', name: 'Lyme', hz: 861.0, effect: 'Lyme treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-lyme-disease-409', name: 'Lyme disease', hz: 864.0, effect: 'Lyme disease elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-lyme-410', name: 'Lyme', hz: 864.0, effect: 'Lyme treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-lyme-411', name: 'Lyme', hz: 868.0, effect: 'Lyme treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-candida-412', name: 'Candida', hz: 873.0, effect: 'Candida treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-streptococcus-413', name: 'Streptococcus', hz: 875.0, effect: 'Streptococcus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-candida-414', name: 'Candida', hz: 877.0, effect: 'Candida treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-streptococci-415', name: 'Streptococci', hz: 880.0, effect: 'Use for Streptococci infecction.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-general-organ-416', name: 'General Organ', hz: 880.0, effect: 'Distended organs', source: 'Rife', category: 'Organ' },
  { id: 'rife-general-overall-system-tonic-417', name: 'General Overall System Tonic', hz: 880.0, effect: 'General tonic', source: 'Rife', category: 'Rife' },
  { id: 'rife-conjunctivitis-418', name: 'Conjunctivitis', hz: 880.0, effect: 'Conjunctivitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-coryza--nose-disorder-419', name: 'Coryza, nose disorder', hz: 880.0, effect: 'Coryza relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-cystitis-bladder-inflammation-420', name: 'Cystitis bladder inflammation', hz: 880.0, effect: 'Cystitis relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-dysmenorrhea---painful-menses-421', name: 'Dysmenorrhea, (painful menses)', hz: 880.0, effect: 'Dysmenorrhea relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-ears--dizziness-422', name: 'Ears, dizziness', hz: 880.0, effect: 'Ears, dizziness relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-edema--lung-swelling--excess-f-423', name: 'Edema (Lung swelling, excess fluids)', hz: 880.0, effect: 'Edema relief', source: 'Rife', category: 'Rife' },
  { id: 'organ-esophagus-424', name: 'Esophagus', hz: 880.0, effect: 'Esophagus support', source: 'Rife', category: 'Organ' },
  { id: 'rife-female-disorder-425', name: 'Female disorder', hz: 880.0, effect: 'Female disorder treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-fistula--ulcer-426', name: 'Fistula, ulcer', hz: 880.0, effect: 'Fistula, ulcer treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-flu--grippe--influenza-427', name: 'Flu, Grippe, influenza', hz: 880.0, effect: 'Flu, Grippe, influenza treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-gangrene--tissue-428', name: 'Gangrene, tissue', hz: 880.0, effect: 'Gangrene treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-gums--inflamed-429', name: 'Gums, inflamed', hz: 880.0, effect: 'Gums, inflamed treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-hemorrhoids-430', name: 'Hemorrhoids', hz: 880.0, effect: 'Hemorrhoids treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-hoarseness-431', name: 'Hoarseness', hz: 880.0, effect: 'Hoarseness relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-infections-432', name: 'Infections', hz: 880.0, effect: 'Infection treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-influenza-433', name: 'Influenza', hz: 880.0, effect: 'Influenza treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-intestines--inflammation-434', name: 'Intestines, inflammation', hz: 880.0, effect: 'Intestines inflammation treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-itching-of-anus--toes----feet-435', name: 'Itching of anus, toes, & feet', hz: 880.0, effect: 'Itching relief', source: 'Rife', category: 'Rife' },
  { id: 'organ-kidney-436', name: 'Kidney', hz: 880.0, effect: 'Kidney support', source: 'Rife', category: 'Organ' },
  { id: 'rife-lassitude--weak--exhausted-437', name: 'Lassitude, weak, exhausted', hz: 880.0, effect: 'Lassitude relief', source: 'Rife', category: 'Rife' },
  { id: 'organ-leukodermia--white-skin-patche-438', name: 'Leukodermia, white skin patches', hz: 880.0, effect: 'Leukodermia treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-leukorrhea--white-vaginal-disc-439', name: 'Leukorrhea, white vaginal discharge', hz: 880.0, effect: 'Leukorrhea treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-liver-enlargement-440', name: 'Liver enlargement', hz: 880.0, effect: 'Liver enlargement treatment', source: 'Rife', category: 'Organ' },
  { id: 'organ-lungs--breathing-441', name: 'Lungs, breathing', hz: 880.0, effect: 'Lungs, breathing support', source: 'Rife', category: 'Organ' },
  { id: 'organ-lymphatic-depressant-442', name: 'Lymphatic depressant', hz: 880.0, effect: 'Lymphatic system support', source: 'Rife', category: 'Organ' },
  { id: 'rife-measles--small-pox--german-mea-443', name: 'Measles, small pox, German measles, mumps, whoopin', hz: 880.0, effect: 'Measles, small pox, German measles, mumps, whooping cough, fever, diphtheria, chicken pox treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-mucous-444', name: 'Mucous', hz: 880.0, effect: 'Mucous treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-neurasthenia--fatigued-445', name: 'Neurasthenia, fatigued', hz: 880.0, effect: 'Neurasthenia relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-nipples--sore-446', name: 'Nipples, sore', hz: 880.0, effect: 'Nipple soreness relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-nose--disorders-447', name: 'Nose, disorders', hz: 880.0, effect: 'Nose disorder treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-oral-inflammation-448', name: 'Oral inflammation', hz: 880.0, effect: 'Oral inflammation treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-osteoarthritis-449', name: 'Osteoarthritis', hz: 880.0, effect: 'Osteoarthritis treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-ovaries-450', name: 'Ovaries', hz: 880.0, effect: 'Ovaries support', source: 'Rife', category: 'Organ' },
  { id: 'rife-pain--paralysis-451', name: 'Pain, paralysis', hz: 880.0, effect: 'Pain, paralysis relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-pains-after-operations-452', name: 'Pains after operations', hz: 880.0, effect: 'Pain relief', source: 'Rife', category: 'Rife' },
  { id: 'organ-parathyroid-453', name: 'Parathyroid', hz: 880.0, effect: 'Parathyroid support', source: 'Rife', category: 'Organ' },
  { id: 'rife-pelvic--disorders-454', name: 'Pelvic, disorders', hz: 880.0, effect: 'Pelvic disorder treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-pericarditis--inflamed-heart-c-455', name: 'Pericarditis, inflamed heart covering', hz: 880.0, effect: 'Pericarditis treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-peritonitis-456', name: 'Peritonitis', hz: 880.0, effect: 'Peritonitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-pharyngitis-457', name: 'Pharyngitis', hz: 880.0, effect: 'Pharyngitis relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-placenta--to-expel-or-afterbir-458', name: 'Placenta, to expel or afterbirth', hz: 880.0, effect: 'Placenta expulsion support', source: 'Rife', category: 'Rife' },
  { id: 'rife-pleurisy-459', name: 'Pleurisy', hz: 880.0, effect: 'Pleurisy treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-pneumonia-460', name: 'Pneumonia', hz: 880.0, effect: 'Pneumonia treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-pruritis--anus-itching-461', name: 'Pruritis, anus itching', hz: 880.0, effect: 'Pruritis relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-rickets-462', name: 'Rickets', hz: 880.0, effect: 'Rickets treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-scarlet-fever-463', name: 'Scarlet fever', hz: 880.0, effect: 'Scarlet fever treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-sexual-diseases-464', name: 'Sexual diseases', hz: 880.0, effect: 'Sexual diseases treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-smallpox-465', name: 'Smallpox', hz: 880.0, effect: 'Smallpox treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-tonsillitis-466', name: 'Tonsillitis', hz: 880.0, effect: 'Tonsillitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-candida-467', name: 'Candida', hz: 883.0, effect: 'Candida treatment', source: 'Clark', category: 'Rife' },
  { id: 'rife-streptococcus-468', name: 'Streptococcus', hz: 885.0, effect: 'Streptococcus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-angel-469', name: 'Angel', hz: 888.0, effect: 'Abundance, prosperity, alignment with universal energy', source: 'Unknown', category: 'Rife' },
  { id: 'rife-plantar-wart-470', name: 'Plantar wart', hz: 915.0, effect: 'Plantar wart elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-plantar-wart-471', name: 'Plantar wart', hz: 918.0, effect: 'Plantar wart elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'super-pineal', name: 'Pineal Activation', hz: 936.0, effect: 'Pineal gland activation, DMT production, third eye opening', source: 'Frequency medicine tradition', category: 'Superhuman' },
  { id: 'org-pineal', name: 'Pineal Gland Resonance', hz: 936.0, effect: 'Pineal gland activation, melatonin and DMT production', source: 'Frequency medicine', category: 'Organ' },
  { id: 'rife-round-worms-474', name: 'Round Worms', hz: 942.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-flukes-475', name: 'Flukes', hz: 945.0, effect: 'Fluke elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'sol-si', name: 'SI — Divine', hz: 963.0, effect: 'Connection with divine consciousness, crown chakra', source: 'Puleo/Horowitz', category: 'Solfeggio' },
  { id: 'rife-si-solfeggio-477', name: 'SI Solfeggio', hz: 963.0, effect: 'God consciousness, spiritual awakening, pineal gland activation, oneness, unity', source: 'Dr. Joseph Puleo', category: 'Rife' },
  { id: 'rife-tesla-478', name: 'Tesla', hz: 999.0, effect: 'Completion and spiritual enlightenment', source: 'Nikola Tesla', category: 'Rife' },
  { id: 'superhuman-superhuman-potential-479', name: 'Superhuman Potential', hz: 999.0, effect: 'Activate superhuman potential', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'gariaev-1000', name: 'Gariaev Linguistic Wave', hz: 1000.0, effect: 'Linguistic wave genome carrier; DNA information field modulation', source: 'Peter Gariaev', category: 'WaveGenetics' },
  { id: 'solfeggio-solfeggio-481', name: 'Solfeggio', hz: 1074.0, effect: 'Spiritual experiences, higher consciousness', source: 'Unknown', category: 'Solfeggio' },
  { id: 'rife-spiritual-frequency-482', name: 'Spiritual Frequency', hz: 1074.0, effect: 'Spiritual frequency', source: 'Meditation Music Library', category: 'Rife' },
  { id: 'solfeggio-solfeggio-483', name: 'Solfeggio', hz: 1152.0, effect: 'Spiritual purification, cleanses negative energies', source: 'Unknown', category: 'Solfeggio' },
  { id: 'solfeggio-solfeggio-484', name: 'Solfeggio', hz: 1174.0, effect: 'Restores equilibrium', source: 'Unknown', category: 'Solfeggio' },
  { id: 'rife-balance-frequency-485', name: 'Balance Frequency', hz: 1174.0, effect: 'Balance', source: 'Meditation Music Library', category: 'Rife' },
  { id: 'organ-bronchioles-opening-486', name: 'Bronchioles opening', hz: 1234.0, effect: 'Easier breathing (asthma)', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'rife-herpes-487', name: 'Herpes', hz: 1489.0, effect: 'Relieves acute outbreak', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-herpes-488', name: 'Herpes', hz: 1500.0, effect: 'Relieves acute outbreak', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-pineal--pituitary--thyroid-489', name: 'Pineal, Pituitary, Thyroid', hz: 1500.0, effect: 'Tonic for pineal, pituitary, thyroid', source: 'Rife', category: 'Organ' },
  { id: 'rife-tuberculosis-virus-490', name: 'Tuberculosis Virus', hz: 1500.0, effect: 'Tuberculosis Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-typhoid-virus-491', name: 'Typhoid Virus', hz: 1500.0, effect: 'Typhoid Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-epididymitis--infammation-uppe-492', name: 'Epididymitis (infammation uppertestes)', hz: 1500.0, effect: 'Epididymitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-osteoarthritis-493', name: 'Osteoarthritis', hz: 1500.0, effect: 'Osteoarthritis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-pelvic--disorders-494', name: 'Pelvic, disorders', hz: 1500.0, effect: 'Pelvic disorder treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-poliomyelitis-495', name: 'Poliomyelitis', hz: 1500.0, effect: 'Poliomyelitis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-sexual-diseases-496', name: 'Sexual diseases', hz: 1500.0, effect: 'Sexual diseases treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-skin-trouble-thrombosis-497', name: 'Skin trouble thrombosis', hz: 1500.0, effect: 'Skin trouble thrombosis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-herpes-498', name: 'Herpes', hz: 1550.0, effect: 'Relieves acute outbreak', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-lupus-vulgaris-499', name: 'Lupus vulgaris', hz: 1550.0, effect: 'Lupus vulgaris treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-shingles--see-herpes-zoster-500', name: 'Shingles (see Herpes Zoster)', hz: 1550.0, effect: 'Shingles treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-tuberculosis-501', name: 'Tuberculosis', hz: 1550.0, effect: 'Tuberculosis treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-herpes-502', name: 'Herpes', hz: 1552.0, effect: 'Herpes elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-typhoid-503', name: 'Typhoid', hz: 1570.0, effect: 'Typhoid treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-eye-504', name: 'eye', hz: 1600.0, effect: 'Major freq. used for eye disorders.', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-eye-disorders-505', name: 'Eye disorders', hz: 1600.0, effect: 'Eye disorder treatment', source: 'James Bare', category: 'Organ' },
  { id: 'rife-tuberculosis-virus-506', name: 'Tuberculosis Virus', hz: 1600.0, effect: 'Tuberculosis Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-typhoid-virus-507', name: 'Typhoid Virus', hz: 1600.0, effect: 'Typhoid Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-eye--glaucoma-508', name: 'Eye, glaucoma', hz: 1600.0, effect: 'Eye, glaucoma treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-hives--urticaria-509', name: 'Hives (urticaria)', hz: 1800.0, effect: 'Hives relief', source: 'Rife', category: 'Rife' },
  { id: 'rife-sexual-diseases-510', name: 'Sexual diseases', hz: 1850.0, effect: 'Sexual diseases treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-typhoid-virus-511', name: 'Typhoid Virus', hz: 1865.0, effect: 'Typhoid virus', source: 'Royal Rife', category: 'Rife' },
  { id: 'rife-typhoid-512', name: 'Typhoid', hz: 1865.0, effect: 'Typhoid elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-sarcoma-virus-513', name: 'Sarcoma Virus', hz: 2000.0, effect: 'Sarcoma Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-cancer-sarcoma-514', name: 'Cancer sarcoma', hz: 2000.0, effect: 'Cancer treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-erysipelas--skin-inflammation-515', name: 'Erysipelas (skin inflammation)', hz: 2000.0, effect: 'Erysipelas treatment', source: 'Rife', category: 'Organ' },
  { id: 'rife-sarcoma-516', name: 'Sarcoma', hz: 2005.0, effect: 'Sarcoma treatment', source: 'James Bare', category: 'Rife' },
  { id: 'rife-sarcoma-517', name: 'Sarcoma', hz: 2008.0, effect: '[Rife freq. for Sarcoma]', source: 'Royal Rife', category: 'Rife' },
  { id: 'organ-psoriasis-518', name: 'Psoriasis', hz: 2008.0, effect: 'Psoriasis treatment', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'rife-non-responsive-cancer-519', name: 'Non responsive Cancer', hz: 2050.0, effect: 'Cancer elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-cancer--sarcoma-520', name: 'Cancer, Sarcoma', hz: 2093.0, effect: 'Cancer treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-sarcoma-virus-521', name: 'Sarcoma Virus', hz: 2100.0, effect: 'Sarcoma Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-basal-cell-skin-carcinoma-522', name: 'Basal Cell Skin Carcinoma', hz: 2116.0, effect: 'Basal cell skin carcinoma elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-carcinoma-virus-523', name: 'Carcinoma Virus', hz: 2120.0, effect: 'Carcinoma Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-chronic-fatigue-syndrome-524', name: 'Chronic Fatigue Syndrome', hz: 2127.0, effect: 'CFS treatment', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-cancer-525', name: 'Cancer', hz: 2127.0, effect: 'Cancer treatment', source: 'James Bare', category: 'Rife' },
  { id: 'rife-cancer--carcinoma--leukemia-526', name: 'Cancer, Carcinoma, Leukemia', hz: 2127.0, effect: 'Cancer treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-leukemia-527', name: 'Leukemia', hz: 2127.0, effect: 'Leukemia treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-carcinoma-528', name: 'Carcinoma', hz: 2128.0, effect: 'Carcinoma elimination', source: 'Rife', category: 'Rife' },
  { id: 'rife-polyps--growths-529', name: 'Polyps, Growths', hz: 2128.0, effect: 'Polyps, growths treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-carcinoma-virus-530', name: 'Carcinoma Virus', hz: 2130.0, effect: 'Carcinoma Virus treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-fruit-flies-531', name: 'Fruit Flies', hz: 2167.0, effect: 'Fruit fly elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'solfeggio-solfeggio-532', name: 'Solfeggio', hz: 2172.0, effect: 'Spiritual enlightenment, expanding awareness', source: 'Unknown', category: 'Solfeggio' },
  { id: 'rife-non-responsive-cancer-533', name: 'Non responsive Cancer', hz: 2180.0, effect: 'Cancer elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-psoriasis-534', name: 'Psoriasis', hz: 2180.0, effect: 'Psoriasis treatment', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'rife-hepatitis-c-535', name: 'Hepatitis C', hz: 2189.0, effect: 'Hepatitis C elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-chlamydia-infections-536', name: 'Chlamydia infections', hz: 2213.0, effect: 'Chlamydia elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-cancer--carcinoma--leukemia-537', name: 'Cancer, Carcinoma, Leukemia', hz: 2217.0, effect: 'Cancer treatment', source: 'Rife', category: 'Rife' },
  { id: 'org-adrenal', name: 'Adrenal Resonance', hz: 2250.0, effect: 'Adrenal tonic, cortisol regulation, stress response balance', source: 'Rife / bioresonance', category: 'Organ' },
  { id: 'organ-chronic-prostatitis-539', name: 'Chronic prostatitis', hz: 2250.0, effect: 'Correct chronic prostatitis', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'organ-adrenals-540', name: 'Adrenals', hz: 2250.0, effect: 'Adrenal tonic', source: 'Rife', category: 'Organ' },
  { id: 'rife-basal-cell-skin-carcinoma-541', name: 'Basal Cell Skin Carcinoma', hz: 2280.0, effect: 'Basal cell skin carcinoma elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'dna-2450', name: 'RF Gene Expression', hz: 2450.0, effect: 'Radiofrequency field shown to alter gene expression patterns', source: 'Electromagnetic research', category: 'DNA' },
  { id: 'dna-rf-fields-543', name: 'RF fields', hz: 2450.0, effect: 'Alter gene expression', source: 'Unknown', category: 'DNA' },
  { id: 'rife-non-responsive-cancer-544', name: 'Non responsive Cancer', hz: 2452.0, effect: 'Cancer elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-herpes-545', name: 'Herpes', hz: 2489.0, effect: 'Long term benefits for herpes', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'organ-cells-of-leydig-in-colon-546', name: 'Cells of Leydig in Colon', hz: 2500.0, effect: 'Tonic for cells of Leydig in colon', source: 'Rife', category: 'Organ' },
  { id: 'rife-pain-547', name: 'Pain', hz: 3040.0, effect: 'Pain relief', source: 'James Bare', category: 'Rife' },
  { id: 'rife-aids-548', name: 'AIDS', hz: 3175.0, effect: 'AIDS treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-round-worms-549', name: 'Round Worms', hz: 3212.0, effect: 'Round worm elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-aids-550', name: 'AIDS', hz: 3275.0, effect: 'AIDS treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-aids-551', name: 'AIDS', hz: 3375.0, effect: 'AIDS treatment', source: 'Rife', category: 'Rife' },
  { id: 'rife-aids-552', name: 'AIDS', hz: 3475.0, effect: 'AIDS treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-bronchioles-opening-553', name: 'Bronchioles opening', hz: 3672.0, effect: 'Easier breathing (asthma)', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'brainwave-central-nervous-system-554', name: 'Central Nervous System', hz: 6000.0, effect: 'Release of emotional problems, blocked seizures, stopped Parkinson\'s tremors', source: 'Rife/Stafford', category: 'Brainwave' },
  { id: 'rife-relieves-the-need-to-worry-555', name: 'Relieves the need to worry', hz: 6130.0, effect: 'Emotional relief', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-cancer-carcinoma--int-ext-556', name: 'Cancer carcinoma, int/ext', hz: 7130.0, effect: 'Cancer treatment', source: 'Rife', category: 'Rife' },
  { id: 'organ-bronchioles-opening-557', name: 'Bronchioles opening', hz: 7344.0, effect: 'Easier breathing (asthma)', source: 'Rife/Stafford', category: 'Organ' },
  { id: 'rife-flu-virus-558', name: 'Flu virus', hz: 7760.0, effect: 'Flu virus elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'rife-flu-virus-559', name: 'Flu virus', hz: 8000.0, effect: 'Flu virus elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'superhuman-superhuman-potential-560', name: 'Superhuman Potential', hz: 8190.0, effect: 'Activate super consciousness', source: 'Various (YouTube)', category: 'Superhuman' },
  { id: 'rife-flu-virus-561', name: 'Flu virus', hz: 8250.0, effect: 'Flu virus elimination', source: 'Rife/Stafford', category: 'Rife' },
  { id: 'wavegenetics-gariaev-laser-562', name: 'Gariaev Laser', hz: 13788.098719721018, effect: 'Audio-range equivalent of 632.8nm He-Ne laser', source: 'Gariaev', category: 'WaveGenetics' },
  { id: 'wavegenetics-he-ne-laser-audio-equivalent-563', name: 'He-Ne Laser Audio Equivalent', hz: 13788.099, effect: 'DNA interaction, wave genetics effects', source: 'Peter Gariaev', category: 'WaveGenetics' },
  { id: 'gariaev-laser', name: 'Gariaev He-Ne Laser', hz: 13788.1, effect: 'Audio-range octave reduction of 632.8nm He-Ne laser; DNA phantom field activation', source: 'Peter Gariaev', category: 'WaveGenetics' },
];

// ─── Category metadata ────────────────────────────────────────────────────────

export interface CategoryMeta {
  id: FrequencyCategory;
  label: string;
  color: string;
  description: string;
}

export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'DNA',
    label: 'DNA',
    color: '#2ECC9A',
    description: 'Frequencies shown to influence DNA repair, gene expression, and cellular coherence',
  },
  {
    id: 'Solfeggio',
    label: 'Solfeggio',
    color: '#9B59B6',
    description: 'Ancient Solfeggio scale — UT through SI and extended tones',
  },
  {
    id: 'Brainwave',
    label: 'Brainwave',
    color: '#3498DB',
    description: 'Delta, theta, alpha, beta, gamma — brainwave entrainment frequencies',
  },
  {
    id: 'Organ',
    label: 'Organ',
    color: '#E67E22',
    description: 'Resonant frequencies of human organs, glands, and body systems',
  },
  {
    id: 'Superhuman',
    label: 'Superhuman',
    color: '#F0A500',
    description: 'Frequencies targeting HGH, muscle fiber, neuroplasticity, mitochondria, telomeres',
  },
  {
    id: 'WaveGenetics',
    label: 'Wave Genetics',
    color: '#E74C3C',
    description: "Gariaev's wave genetics frequencies including He-Ne laser audio equivalent",
  },
  {
    id: 'Rife',
    label: 'Rife / MOR',
    color: '#1ABC9C',
    description: "Royal Raymond Rife's Mortal Oscillatory Rates and CAFL frequencies",
  },
  {
    id: 'Schumann',
    label: 'Schumann',
    color: '#27AE60',
    description: "Earth's electromagnetic resonance harmonics — 7.83 Hz and overtones",
  },
];

export const CATEGORY_COLOR: Record<FrequencyCategory, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c.color])
) as Record<FrequencyCategory, string>;

// ─── Default enabled frequencies (one from each category) ────────────────────

export function getDefaultEnabled(): FrequencyEntry[] {
  const seen = new Set<FrequencyCategory>();
  const defaults: FrequencyEntry[] = [];
  // Priority picks
  const priority = [
    'sol-mi',        // 528 Hz DNA repair
    'schumann-1',    // 7.83 Hz Earth resonance
    'bw-gamma',      // 40 Hz gamma
    'gariaev-laser', // 13788 Hz He-Ne laser equivalent
    'super-hgh',     // 111 Hz HGH
    'org-heart',     // 1.2 Hz heart
    'dna-adey',      // 16 Hz Adey window
    'sol-ut',        // 396 Hz UT
  ];
  for (const id of priority) {
    const f = FREQUENCY_LIBRARY.find((e) => e.id === id);
    if (f && !seen.has(f.category)) {
      seen.add(f.category);
      defaults.push(f);
    }
  }
  // Fill remaining categories
  for (const f of FREQUENCY_LIBRARY) {
    if (!seen.has(f.category)) {
      seen.add(f.category);
      defaults.push(f);
    }
    if (seen.size === CATEGORIES.length) break;
  }
  return defaults;
}
