/**
 * lib/scalar-encoder.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * BioSonify Bearden Scalar Wave Phase-Conjugate Encoder
 *
 * Tom Bearden's scalar wave theory holds that longitudinal (scalar)
 * electromagnetic waves can be generated by superposing two transverse EM
 * waves that are 180° out of phase. Their transverse components cancel
 * (producing a "zero-vector" field in 3-space), but the scalar potential
 * — the Whittaker decomposition — remains and propagates as a longitudinal
 * pressure wave that interacts directly with biological systems, including DNA.
 *
 * In audio, this is implemented as a PHASE-CONJUGATE PAIR:
 *
 *   Channel A (original signal)       : s(t)
 *   Channel B (phase conjugate)       : s*(t) = s(-t) — time-reversed copy
 *
 * When both channels are played simultaneously through headphones:
 *   • The transverse (pressure) components partially cancel in the room
 *   • The scalar (longitudinal) component — the information structure —
 *     is preserved and propagates through the listener's body
 *   • DNA, as a liquid-crystal antenna (Gariaev, Poponin), transduces
 *     this scalar field back into coherent EM information
 *
 * Implementation:
 *   • The encoder takes a stereo buffer and produces a 4-channel output:
 *       Ch 1 (L original), Ch 2 (R original),
 *       Ch 3 (L conjugate = time-reversed L), Ch 4 (R conjugate = time-reversed R)
 *   • For a 2-channel headphone output, Ch3 and Ch4 are mixed into Ch1 and Ch2
 *     at a configurable conjugate_mix ratio (default 0.5)
 *   • The result is a stereo signal where the forward and conjugate waves
 *     coexist, creating the scalar interference pattern inside the listener
 *
 * Bearden references:
 *   • Bearden (2002) — Energy from the Vacuum
 *   • Whittaker (1903) — On the partial differential equations of mathematical physics
 *   • Poponin (1995) — The DNA Phantom Effect
 *   • Gariaev (1994) — Wave-based genome
 */

// ─── Scalar Encoding ──────────────────────────────────────────────────────────

/**
 * Apply Bearden scalar phase-conjugate encoding to a stereo buffer.
 *
 * The conjugate signal is the time-reversed version of the original.
 * Mixed at `conjugateRatio` (0 = no scalar, 1 = full conjugate, 0.5 = balanced).
 *
 * @param stereoIn      - Input stereo interleaved Float32Array (L,R,L,R,...)
 * @param conjugateRatio - How much of the phase-conjugate to mix in (0–1)
 * @returns Scalar-encoded stereo interleaved Float32Array
 */
export function applyScalarEncoding(
  stereoIn: Float32Array,
  conjugateRatio: number = 0.5
): Float32Array {
  const n = stereoIn.length;
  const frames = n / 2;
  const out = new Float32Array(n);

  // Build time-reversed (phase-conjugate) version
  const conjugate = new Float32Array(n);
  for (let i = 0; i < frames; i++) {
    const mirrorFrame = frames - 1 - i;
    conjugate[i * 2]     = stereoIn[mirrorFrame * 2];
    conjugate[i * 2 + 1] = stereoIn[mirrorFrame * 2 + 1];
  }

  // Mix original + conjugate
  const forwardGain = 1.0;
  const conjugateGain = conjugateRatio;

  for (let i = 0; i < n; i++) {
    out[i] = stereoIn[i] * forwardGain + conjugate[i] * conjugateGain;
  }

  // Normalize to prevent clipping
  let peak = 0;
  for (let i = 0; i < n; i++) {
    const abs = Math.abs(out[i]);
    if (abs > peak) peak = abs;
  }
  if (peak > 1.0) {
    const inv = 1 / peak;
    for (let i = 0; i < n; i++) out[i] *= inv;
  }

  return out;
}

/**
 * Generate a scalar carrier wave — a pure sine wave with its phase conjugate
 * mixed in. This produces the "zero-vector" interference pattern described
 * by Bearden as the mechanism for scalar wave generation.
 *
 * @param freqHz      - Carrier frequency in Hz
 * @param sampleRate  - Sample rate (default 44100)
 * @param durationSec - Duration in seconds
 * @param conjugateRatio - Phase conjugate mix ratio (0–1)
 * @returns Stereo interleaved Float32Array
 */
export function generateScalarCarrier(
  freqHz: number,
  sampleRate: number = 44100,
  durationSec: number = 5,
  conjugateRatio: number = 0.5
): Float32Array {
  const frames = Math.floor(durationSec * sampleRate);
  const mono = new Float32Array(frames);
  const phaseInc = (2 * Math.PI * freqHz) / sampleRate;

  for (let i = 0; i < frames; i++) {
    mono[i] = Math.sin(i * phaseInc);
  }

  // Convert to stereo
  const stereo = new Float32Array(frames * 2);
  for (let i = 0; i < frames; i++) {
    stereo[i * 2]     = mono[i];
    stereo[i * 2 + 1] = mono[i];
  }

  return applyScalarEncoding(stereo, conjugateRatio);
}

/**
 * Apply scalar encoding to a mono buffer, returning stereo.
 * The left channel carries the forward wave, the right channel carries
 * the phase-conjugate wave. When played simultaneously through headphones,
 * the scalar interference pattern is created inside the listener's head.
 *
 * This is the "split-channel scalar" mode — the most direct implementation
 * of Bearden's opposing-wave model.
 *
 * @param mono        - Input mono Float32Array
 * @param conjugateRatio - Amplitude of conjugate channel (0–1)
 * @returns Stereo interleaved Float32Array
 */
export function monoToScalarStereo(
  mono: Float32Array,
  conjugateRatio: number = 1.0
): Float32Array {
  const n = mono.length;
  const stereo = new Float32Array(n * 2);

  for (let i = 0; i < n; i++) {
    const forward = mono[i];
    const conjugate = mono[n - 1 - i]; // time-reversed = phase conjugate
    stereo[i * 2]     = forward;
    stereo[i * 2 + 1] = conjugate * conjugateRatio;
  }

  // Normalize
  let peak = 0;
  for (let i = 0; i < stereo.length; i++) {
    const abs = Math.abs(stereo[i]);
    if (abs > peak) peak = abs;
  }
  if (peak > 1.0) {
    const inv = 1 / peak;
    for (let i = 0; i < stereo.length; i++) stereo[i] *= inv;
  }

  return stereo;
}
